### PR TITLE
fix(autoflight): engage managed speed after v2 confirm

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Fixes an issue where managed speed would not engage automatically when V2 is confirmed or re-entered after a departure runway change. The V-speed local vars were not being reset when the Vspeed properties were. The fix ensures the localvars are always set when the FMS properties are set by implementing a setter.

Also removes an erroneous V2 local var from the docs, which existed only in the docs.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Set up for departure, entering the runway, and V2 on the PERF TO page; make sure managed speed engages and the V2 speed is shown above the PFD speed tape.
Change to a different departure runway, note that managed speed disengages and the speed target returns to 100 knots.
Confirm the V2 speed by pressing the LSK next to it on the PERF TO page; ensure that managed speed re-engages, and the V2 is shown above the speed tape.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by BlueberryKing — APPROVED** [review]
LGTM! I see luke and don are requested, so they should look over it as well.

**Comment by tracernz** [comment]
Luke because I know he’s also working on FMGC and FCU in his PR, and Don because he reported this issue.

**Comment by pilotseyea350** [comment]
Quality Assurance Trainee Report

Discord          : piloteyesa350
Object of testing: #8395 
Tier of Testing  : 1
Date             : 09/01/2024

Testing Process: 
1. Spawn at EDDF RWY25C
2. Exit RWY25C
3. Setup INIT A  (Flight : EDDF-EDDM; Flight Number : DEV123 ; CI :5 ; FL290)
4. Setup IINIT B (ZFW : 42.5 CG : 30.0)
5. Setup F-PLN Page for departure out of RWY25C
6. Observe speed is 100
7. Setup PERF page (Flaps : 1 ; FLX : 67) and enter V-Speed
8. Observe Speed Managed
9. Setup F-PLN Page for departure out of RWY07C
10. Observe speed is 100
11. Setup PERF page (Flaps : 1 ; FLX : 67) and enter V-Speed
12. Observe speed managed
13. Enter the RWY25C
14. Setup F-PLN Page for departure out of RWY25C
15. Observe speed is 100
16. Setup PERF page (Flaps : 1 ; FLX : 67) and enter V-Speed


Negatives:       
V1 and VR are not displayed correctly during Take-Off roll
V1 and VR were 121kts but blue speed was 235

Testing Results: 
Not Passed

Conclusions: 
Regression as V2 speeds are correct, but not V1 nor VR

Media:

Before Line-up; before PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 09 - 22 33 00 10


Before Line-up; after PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 09 - 22 33 15 79


Before Line-up; After RWY Change; Before PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 09 - 22 33 47 99


Before Line-up; After RWY Change; After PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 09 - 22 34 11 07


After Line-up; After (another) RWY Change; Before PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 09 - 22 35 41 94

After Line-up; After RWY Change; After PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 09 - 22 35 50 47

Steps to reproduce the issue :

Download the A32NX folder from this PR
Paste into Community
Launch a flight anywhere on the runway
Setup INIT A, INIT B, F-PLN and PERF pages
Observe V2 Magenta 
Compare MCDU V1 speed and PFD Blue Speed

**Comment by pilotseyea350** [comment]
Quality Assurance Trainee Report

Discord : piloteyesa350
Object of testing: #8395
Tier of Testing : 1
Date : 10/01/2024

Testing Process:

1. Spawn at gate A28 at EDDF
2. Perform Pre-Startup Checks 
3. Follow Cockpit Preparation Items
4. Setup INIT A (Flight : EDDF-EDDM; Flight Number : DEV123 ; CI :5 ; FL290)
5. Setup INIT B (ZFW : 42.5 CG : 30.0 FOB : 3.8)
6. Force ADIRS Alignement (flyPAD Settings -> Realism -> Switch ADIRS Align Time from Real to Instant
7. Setup F-PLN Page for departure out of RWY25C
8. Setup PERF page (Flaps : 1 ; FLX : 67) and enter V-Speed
9. Observe V2 Magenta & V1 Blue
10. Setup F-PLN Page for departure out of RWY07C
11. Observe speed is 100
12. Setup PERF page (Flaps : 1 ; FLX : 67) and enter V-Speed
13. Observe V2 Magenta & V1 Blue

Extra steps :
P/B with GSX and taxi to RWY07C & Take-Off
Observe speeds displayed on speed tape according to V-Speeds

Negatives:       
After the RWY Change, the green line between RWY07C and 
1838 disapears
Added Waypoint PDB01 25nm out of RWY07C and on Heading 068
Line Still doesn't appear
Switched to SID ANEKI1X and Green Line appeared again

Steps to reproduce : 
Follow the Testing Process
+ Add waypoint by typing EDDF07C/068/25 and using the LSK after 1838


Testing Results:
Passed

Media:
Before RWY Change; After PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 10 - 23 32 44 77

After RWY Change; Before PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 10 - 23 33 02 36

After RWY Change; After PERF Calculations :
Microsoft Flight Simulator Screenshot 2024 01 10 - 23 34 28 07

After RWY Change; After PERF Calculations; Before Choosing SID :
Microsoft Flight Simulator Screenshot 2024 01 10 - 23 38 07 40

After RWY Change; After PERF Calculations; After Choosing ANEKI 1X :
Microsoft Flight Simulator Screenshot 2024 01 10 - 23 38 29 04

On Take-Off Roll before rotate
Microsoft Flight Simulator Screenshot 2024 01 10 - 23 51 00 86

**Comment by pilotseyea350** [comment]
> Can you please open an issue for the track line problem? I am quite confident that's not related.

Yep will do

**Pull request merged**
