### PR TITLE
fix(efb): pax changes

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #[issue_no]

## Summary of Changes

* reduced carbon footprint by 6.74%
* added new luxury forward ballast class of seating vs squashed sardine class
* more room for activities i.e. Swiftie concert on board (TODO: boris)
* Deprecated "fill" field in payload json format

Note: EFB only change.

## Screenshots (if necessary)

image

## References

repsol's onlyfans

## Additional context

Discord username (if different from GitHub): 2cas

## Testing instructions

1. Regression Test A320 payload page (fill in desired pax and ensure that any number of pax can be filled). 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by frankkopp — APPROVED** [review]
Didn't you change the overall pax number? 
If so shouldn't the defaults here be changed?
`fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A380_842/A380Payload.tsx` 
line 54+

**Comment by 2hwk** [comment]
> Didn't you change the overall pax number? If so shouldn't the defaults here be changed? `fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A380_842/A380Payload.tsx` line 54+

This is the refresh Interval not default pax number (can probably be deleted without any impact whatsoever, but I didn't want to add more things to test)

**Comment by Letreivchen** [comment]
Quality Assurance Tester Report

Discord          : Letreiv
Object of testing: (#8524 )
Tier of Testing  : (1)
Date             : (26/02/2024)

Testing Process: 
- Checked that random pax numbers from 0 to 174 can be filled
- Checked simbrief sync with 22 different flight plans

Negatives:       
Out of the 22 times, 3 times one passenger was missing and 2 times 2 passengers were missing

Testing Results: 
Not passed

Conclusions: 
reproducible combinations i found

- 173 in simbrief gives 171 in the efb
- 172 in simbrief gives 171 in the efb
- 171 and 174 works 

Media:       
none

**Comment by 2hwk** [comment]
I'll try to take a look over the weekend (but no promises)

**Comment by alepouna** [comment]
QA Report

Discord: alepouna
Object of testing:  #8524
Tier of Testing : 1
Date : 2/3/2024

Testing Process:
A380
- Attempt any passenger boarding procedure with either set numbers or simbrief import

Negatives:
No change in passenger number, boarding even on instant remains stuck on 'boarding' and CG graph moves to estimated new (?) CG but resets when boarding is stopped. 

Testing Results:
Not Passed

**Comment by alepouna** [comment]
discard above QA report, I did a clean installation and its working. new report soon.

**Comment by alepouna** [comment]
QA Report

Discord: alepouna
Object of testing: https://github.com/flybywiresim/aircraft/pull/8524
Tier of Testing : 1
Date : 2/3/2024

Testing Process:
A320 + A380
- Perform boarding procedures with either a random set numbers or random Simbrief imports

Testing Results:
Passed

Notes: 
6/10 art

**Comment by Letreivchen** [comment]
Quality Assurance Tester Report

Discord : Letreiv
Object of testing: (#8524 )
Tier of Testing : (1)
Date : (07/03/2024)

Testing Process:

Checked that random pax numbers from 0 to 174 can be filled
Checked simbrief sync with a couple random pax numbers
checked that 172 in simbrief gives 172 in the efb
checked that 173 in simbrief gives 173 in the efb

Negatives:
none

Testing Results:
Passed

Conclusions:
fixed now

Media:
none

**Pull request merged**
