### PR TITLE
feat: mcdu annunciator lights

### LINKED ISSUE #5140: Emissives for MCDU at the top and sides
### Aircraft Version

Development

### Description

MCDU should have 5 lights on top and some on the sides.

I'm creating this issue to split up and close #528.

### References (optional)

image

### Additional info (optional)

_No response_

### Discord Username (optional)

SjotgunSjonnie#9623

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #5140

## Summary of Changes

Adds annunciator lights on either side and at top of the MCDUs... They are not yet hooked up to message system logic (future work that @derl30n might do) or FM failures/modes, but they will turn on with ANN LT TEST, or when the Lvars are set manually.

While editing the textures... in the interests of not increasing the git repo size any more than necessary... I took the liberty of making another small change while I'm here... The FCU and ECAM buttons now have a subtle effect where the LEDs are visible if you look closely...

## Screenshots (if necessary)

Day, test:
image
Night, dim, on except for the blank one:
image

image

## References

image

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check general decals in the flight deck with integral lighting on and off (texture changed in this PR). Check MCDU annunciator lights come on when ANN LT switch is in the test position on the overhead.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by jcalor** [comment]
Quality Assurance Tester Report

Discord          : Jorge#6816
Object of testing: #6008 
Tier of Testing  : 1
Date             : 16/10/2021

Testing Process: 

Spawned loaded on RWY _with DEV version_ (to compare EFIS lights with this PR).
Spawned loaded on RWY _with this PR_. ANN LT switch to TEST, compared lights with latest DEV version - checked. 
MCDU annunciator lights working well - checked.

Negatives:       

This small bar should be slightly finer in accordance to this image (https://media.discordapp.net/attachments/739223532269076561/898854881203470346/IMG_20211016_104602.jpg?width=895&height=671)
image

FM word from FAIL FM, on the left side should be in orange, not in white (https://media.discordapp.net/attachments/739223532269076561/898854882268811314/IMG_20211016_104550.jpg?width=503&height=671)
image

MDCU MENU has the same problem, should be in orange (https://media.discordapp.net/attachments/739223532269076561/898854881736163348/IMG_20211016_104555.jpg?width=503&height=671)
image

Finally, it´s me or here says FMI, instead of FM1? 🤔 https://media.discordapp.net/attachments/739223532269076561/898854880691761222/IMG_20211016_104606.jpg?width=895&height=671
image

Testing Results: Not passed

Conclusions: PR works well but there´s a few small color bugs (they differ from real Airbus). Anyways, super job!

Media:

DEV
image
PR
image
image

**Comment by derl30n** [comment]
@jcalor 

> FM word in FAIL FM should be in orange https://media.discordapp.net/attachments/739223532269076561/898854882268811314/IMG_20211016_104550.jpg?width=503&height=671 image
> 

> MCDU MENU has the same problem https://media.discordapp.net/attachments/739223532269076561/898854881736163348/IMG_20211016_104555.jpg?width=503&height=671 image
> 

Following private references, FAIL is amber. MCDU MENU and FM are white.

For the top bar, FM1 and FM2 as well as IND are amber.

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #6008
Tier of Testing: 1
Date: 16/10/2021

Testing Process:
- Spawned C&D at EDDP
- Started aircraft
- Turned on ANN LT TEST

MCDU: FM, MCDU MENU white; FAIL, FM1, IND, bar and FM2 amber; RDY green (Image1)

Negatives: 
- FM1 shows FMI (Image1)
- LED dots texture cut off (Image2), mostly on radio buttons (Image3) 

Testing Results: Not passed
Conclusions: Maybe the LED texture cut off is to the Asobo model...?

Hope this helps :-)


Image1


Image2


Image3

**Comment by bouveng** [comment]
@tracernz Hi M! It seems like the texture is to wide for the UV. There is no rounded corners. Can it be widened? 

bars
fd

Br.

**Comment by tracernz** [comment]
> @tracernz Hi M! It seems like the texture is to wide for the UV. There is no rounded corners. Can it be widened?
> 
> bars fd
> 
> Br.

The dots were adjusted to match the UV for the glareshield and ECAM buttons in https://github.com/flybywiresim/a32nx/pull/6008/commits/7209c97e0c7c7c4ae4216fbb86980c0d317821bb. Looks like you have the texture from the older commit there. They still aren't perfect for the RMP, so I may need to abandon the idea.

**Comment by marcman86** [comment]
> Very slight misalignment on the RMP, but can't be fixed without changing UVs... I think it's fine as-is:

Cant this been done by drawing the white LED spots on the texture a little bit more together (to the center)?

**Comment by tracernz** [comment]
Okay, we're back to white. Should be good to go.

**Comment by marcman86** [comment]
Retested: Now we have this

**Comment by jcalor** [comment]
Quality Assurance Tester Report

Discord          : Jorge#6816
Object of testing: #6008
Tier of Testing  : 1
Date             : 18/10/2021

Testing Process: 

Test #2 for this PR after some bug solvings. Same procedure as previous test - everything works well and bugs are corrected.

Negatives: N/A

Testing Results: Passed

Conclusions: Nothing to add - works as expected.

Media:       

image
image

**Pull request merged**
