### PR TITLE
fix(a380x/jetway): Jetway connections tweak

### LINKED ISSUE #9366: Move jetway positioning when docked to include opened aircraft door
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

Connecting the jetway is working perfectly fine, but the aircraft door is always outside of the connected jetway (I guess because it is very wide), and to the right of the door, there is so much empty space included in the jetway that makes me wonder if the jetway connection point can be moved further left. See reference pictures for visuals.

### Expected behavior

As said, everything works as expected, but moving it further left would look better and from the outside. Clearly this problem can't be solved for every jetway existing because they come in different forms and sizes, but the doors lurking out would be less frequent.

Maybe this also a sim limitation and can't be changed and only scenery devs can change the jetway connection, but I have no knowledge about that.

### Steps to reproduce

1. Connect the jetway and look how the door clips out of the jetway.

### References (optional)

**for example iniBuilds OMDB**

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by C-Schaffhausen**
Updated interactive_point to tweak Jetway connection to main deck door L1 (better fit) and L2 (jetway fully covers opened door)

Fixes #9366 

Summary of Changes
Updated interactive_point.0 and interactive_point.2 in flight_model.cfg for better jetway connection, with changelog this time.

Main deck L1 - better jetway fit
Main deck L2 - jetway cover opened door fully
(Note: Some jetways are smaller in size and would not cover the opened doors properly! The tweak here is confirmed to work when using Inibuild EGLL jetways)

Screenshots (if necessary)
Microsoft Flight Simulator Screenshot 2024 11 05 - 21 03 26 84
Microsoft Flight Simulator Screenshot 2024 11 05 - 21 04 26 61

References
Additional context
Discord username (if different from GitHub): C.Schaffhausen

Testing instructions
Load into the sim and dock jetways to the aircraft to test both doors
How to download the PR for QA
Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

Make sure you are signed in to GitHub
Click on the Checks tab on the PR
On the left side, find and click on the PR Build tab
Click on either flybywire-aircraft-a320-neo or flybywire-aircraft-a380-842 download link at the bottom of the page

### CODE REVIEW

**Comment by alepouna** [comment]
Needs changelog conflict resolution

**Comment by C-Schaffhausen** [comment]
Thanks for the feeback, it's my first time using github, do I just paste my changelog at the lowest line? Thank you!

**Comment by C-Schaffhausen** [comment]
Changelog added

**Comment by alepouna** [comment]
Yep changelog looks good, thank you!

**Review by 2hwk — APPROVED** [review]

**Comment by Awemeter** [comment]
I think you should base your changes off of the default jetway to ensure a wider range of compatibility. I have tried default jetways, FSDT KORD jetways, and ini builds OMAA jetways and the door is still clipping through the side and the rubber seal is going through the airplane.

**Comment by C-Schaffhausen** [comment]
> I think you should base your changes off of the default jetway to ensure a wider range of compatibility. I have tried default jetways, FSDT KORD jetways, and ini builds OMAA jetways and the door is still clipping through the side and the rubber seal is going through the airplane.

I'll take a look, there's no magic way to tweak it quickly so it's a trial-and-error thing. I'll check again when I'm not flying!

**Comment by C-Schaffhausen** [comment]
Tweaked jetway positions again so most jetways would cover the doors completely. Note that different developers has different jetway configuration and it would be impossible to have everyone docked perfectly.

**Comment by C-Schaffhausen** [comment]
Tweak complete, ready for merge

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord Username: 2cas
Object of testing: #9429
Aircraft: A380X
Tier of Testing: 1
Date: 10/11/2024

Testing Process: 

- [x] Loaded in to OMDB A11  - Default scenery
- [x] Tested with Jetway on M1L and M2L

M1L
image


M2L
image

- [x] Loaded in WSSS F31 - Default Scenary
- [x] Tested with Jetway on M1L and M2L

M1L

image

Reference Photo:
image


M2L

image


Testing Results: 
Passed

Conclusions: 
LGTM

**Comment by 2hwk** [comment]
Merged, congratulations on your first contribution to the FBW project.

**Pull request merged**
