### PR TITLE
fix(fms): discard approaches with no runway

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Fixes an issue where blank lines were shown on the approach page when an approach does not match any runway in the database (can occur with third party navdata). We now properly skip over those approaches. This also re-enables circling approaches which have been filtered out since a little while ago.

## Screenshots (if necessary)

The issue:
image
The offending navdata:
image

After fix:
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Test with and without Navigraph navdata if possible. Check that no blank lines appear in the approach page for CYYT. Check some other airports you know to ensure all the approaches appear.
Check that LGKR VOR-A circling approach is available.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by tshomas** [comment]
Just a question in regards to this

So at current dev, cloudbreak procedures come up as the blank titles, as they don't have runway assignments in real life either. For example LGKR:
image

However selecting an untitled procedure still allows for that procedure to be loaded:
image

image

image


So this PR will remove the ability to load the cloudbreak procedures completely, but will tidy up the menu, is this intentional?

**Comment by tracernz** [comment]
Good point. Seems like the existing logic was not quite right.

**Review by BlueberryKing — APPROVED** [review]
LGTM

**Comment by KOWA380** [comment]
Quality Assurance Trainee Report

Discord : KOWALSKI#7268
Object of testing: https://github.com/flybywiresim/aircraft/pull/8398
Tier of Testing : (1)
Date : 18/01/2024

Testing Process:

   1. Log into Game

   2. Launch aircraft

   3. Initialize flight for CYYT or LGKR

   4. Go to F-PLN page and select destination 

   5. Select Arrivals

   6. Check that no blank lines appear in the approach page for CYYT

   7. Check that LGKR VOR-A circling approach is available.

Negatives:

N/A

Conclusions:
Working as expected

Media:
CYYT arrivals
[Screenshot 2024-01-18 182932](https://github.com/flybywiresim/aircraft/assets/156888172/d0af4804-5756-45c7-9dca-06c3135a53a4)

LGKR VOR-A
[Screenshot 2024-01-18 183054](https://github.com/flybywiresim/aircraft/assets/156888172/e4c7c66b-2f55-4428-8c70-334b1762c184)

CYYT arrivals after removing NAVIGRAPH database
[Screenshot 2024-01-18 183931](https://github.com/flybywiresim/aircraft/assets/156888172/8bde7fcd-f999-4e28-aeeb-77ab6a9a6fe5)

LGKR VOR-A after removing NAVIGRAPH database
[Uploading Screenshot 2024-01-18 184011.png…]()

Other airport arrivals tested : VIDP/VILH
[Screenshot 2024-01-18 183159](https://github.com/flybywiresim/aircraft/assets/156888172/94faf88a-c2c6-4b95-8b42-3a8a0b2c4153)
[Screenshot 2024-01-18 183408](https://github.com/flybywiresim/aircraft/assets/156888172/cf974380-04c4-42dd-b940-c0c9fa91664b)

**Pull request merged**
