### PR TITLE
fix(efb): add required pages for unified efb

### PR DESCRIPTION
**Pull request by masterrob94**
## Summary of Changes
Add required pages for EFB (A20N & A380 split)

Discord username (if different from GitHub): masterrob94 (Rob B#7923)

## Testing instructions
Open EFB and check if the changed pages are loaded up correctly (modify panel.cfg if not on A380)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by 2hwk** [comment]
This appears to duplicate functionality that will already be provided by merging https://github.com/flybywiresim/aircraft/pull/8180

**Comment by masterrob94** [comment]
> This appears to duplicate functionality that will already be provided by merging #8180

It wasn't clear to see that you have added that. My Idea was to make this not only compatible for A380. It should be easier/similar to the already existed Payload Pages for both, where you can add varaints with minor modifications. We use this similar apporach on our mod to provide more than 2 variants

**Comment by 2hwk** [comment]
note that there are merge conflicts after #8180 was merged, please merge from origin master again or rebase your changes, thanks

**Comment by auroraisluna** [comment]
what are these "required" & changed pages? Asking for QA instructions :) (for when its ready!)

**Comment by masterrob94** [comment]
> what are these "required" & changed pages? Asking for QA instructions :) (for when its ready!)

visually there is nothing changed. The way both pages (Overview and Flight widget) get information is based on the airframe parameter from panel.cfg like many pages like ground services (after this PR) and payload (before this PR), which is implemented already

**Comment by auroraisluna** [comment]
> > what are these "required" & changed pages? Asking for QA instructions :) (for when its ready!)
> 
> visually there is nothing changed. The way both pages (Overview and Flight widget) get information is based on the airframe parameter from panel.cfg like many pages e.g. ground services (after this PR) and payload (before this PR), which is implemented already

Ah, I see, Thanks for the clarification!

**Comment by 2hwk** [comment]
Pending to be Closed as https://github.com/flybywiresim/aircraft/pull/8330 has cherry picked this change as part of a wider EFB refactor PR

**Pull request closed without merging**
