### PR TITLE
fix(fadec): fuel consumption at higher simrates

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

- Makes some fixes to build env. and scripts, especially ensuring the igniter build fails when the cmake script or build fails.
- Adds a new simulation delta time to the C++ framework, which works similarly to the delta time in the old FADEC, accounting for simrate.
- Fixes the delta time used for FADEC calculations to use the sim-rate dependent simulation delta time.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Note: I recommend https://flightsim.to/file/45543/sim-rate-selector for controlling the sim rate if you don't already have a convenient means of doing so.

- Setup a flight at a cruise level in ISA weather (clear skies preset is okay), and achieve stable flight with the AP and ATHR ON.
- Use the chrono to time how long it takes to consume a given quantity of fuel with simrate at 1x (suggest 100 kg or more). The FOB on the EWD is good enough if you pick a fuel quantity of at least 100 kg.
- Increase the simrate to 4x
- Use the chrono to time how long it takes to consume the same quantity of fuel with simrate at 4x.
- The chrono time should be approximately the same, as the chrono will run at 4x wallclock time when the simrate is 4x.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by frankkopp** [comment]
Can we add this to this PR?

file: .clang-format
```
AlignArrayOfStructures: Left
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: Consecutive
AlignConsecutiveShortCaseStatements:
  Enabled: true
```

**Review by frankkopp — APPROVED** [review]
Really nice improvements.

**Comment by 2hwk** [comment]
Note: Won't be affected by the upcoming merge freeze.

**Comment by Saschl** [comment]
Quality Assurance Report

Discord : saschl
Object of testing: https://github.com/flybywiresim/aircraft/pull/8636
Tier of Testing : 2
Date : 25.04.2024

Testing Process:

Level flight at 11.000 feet with Clear Skies preset.

Observed fuel consumption of 100kg with chrono.

1x simrate -> took 2:50 to consume 100kg
4x simrate -> took 2:49 to consume 100kg (I am not very precise with timing and the error is within margin imo)


Also no fuel consumption observed during sim pauses.

Negatives:
N/A

Testing Results:
Passed

Conclusions:
Working as expected


Media:

Screenshot 2024-04-25 230538



image

**Pull request merged**
