### PR TITLE
feat(ci): GitHub Action for QA labels

### PR DESCRIPTION
**Pull request by auroraisluna**
Fixes #[issue_no]

## Summary of Changes
Introduces a GitHub Action (created by me https://github.com/auroraisluna/qa-labels-for-prs) with the purpose of automatically labeling incoming PRs when they are marked via a QA report or by a developer as "Ready to test" 

This does not change the workflow of QA, however it simply adds labels depending on the QA report. 

Example:
image

**For maintainers**: 
This action requires `pull_requests` write permission for the labels. 
Action repo: https://github.com/auroraisluna/qa-labels-for-prs

Discord username (if different from GitHub): alepouna

## Testing instructions

This does not require any aircraft change. Once this Action is enabled, any new QA comments in PRs will have labels. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by auroraisluna** [comment]
I have created this repo to demonstrate how it works: https://github.com/auroraisluna/qa-labels-for-prs-test/pull/1, feel free to explore.

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
At least code wise looks ok, approved

**Comment by auroraisluna** [comment]
that was not my intention

**Comment by auroraisluna** [comment]
Not RTT yet, fixing a potential bug.

**Comment by auroraisluna** [comment]
GitHub uses v1.0.0 on my personal testing repo but it should use 1.0.2. If someone can test this out - RTM :)

**Pull request merged**
