### PR TITLE
fix(mcdu): remove v-speed auto-fill

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Removes the V-speed auto-fill function in the MCDU, as it is no longer relevant after https://github.com/flybywiresim/aircraft/pull/8678 merges and not realistic.

Not to be merged until after #8678.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Try the V-speed LSKs on PERF TO with empty scratchpad and ensure you get "FORMAT ERROR". Try entering speeds properly and ensure it works. Make sure departure runway is set in the flightplan, ZFW and FOB are entered on INIT B (or just ZFW if engines running). Try entering speeds that are too low (but still valid within the range 90-Vmo) and ensure you get a message saying they're too low on the scratchpad.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by Maximilian-Reuter — APPROVED** [review]
LGTM

**Review by donstim — APPROVED** [review]
Looks good to me.

**Comment by BlueberryKing** [comment]
Nice work! This will require an update to the documentation and clear communication from our side. Everyone is used to this working in our plane.

**Comment by tracernz** [comment]
Yep, the suggestion for this PR actually came out of writing the docs 👍.

**Comment by alepouna** [comment]
QA Report

Discord: alepouna
Object of testing: #8712
Tier of Testing: 1
Date: 28/6/2024

Testing Process:
- Click LSK for Vspeeds, FORMAT ERROR as expected
- [FAIL] Enter extremely low values (80), value is accepted, no speed too low
- Enter invalid values (0-89), ENTRY OUT OF RANGE.  

Testing Results:
Not Passed

Negatives: 
No "speed too low" scratchpad amber message shown

**Comment by tracernz** [comment]
Oops, I missed a step. You have to enter flaps before V-speeds can be checked.
image

**Comment by alepouna** [comment]
> Oops, I missed a step. You have to enter flaps before V-speeds can be checked. image

Flaps were entered (as I am pretty sure the calculator doesnt work anyways without one) I used 2 iirc.

**Comment by tracernz** [comment]
And the accepted range is 90-Vmo.

**Comment by alepouna** [comment]
QA Report

Discord: alepouna
Object of testing: https://github.com/flybywiresim/aircraft/pull/8712
Tier of Testing: 1
Date: 28/6/2024

Testing Process:

- Fill init A/B 
- Click LSK for Vspeeds, FORMAT ERROR as expected
- Enter extremely low values (80), value is accepted, no speed too low
- Enter invalid values (0-89), ENTRY OUT OF RANGE.

Testing Results:
Passed

**Pull request merged**
