### PR TITLE
fix(A380X): Fix throttle calibration for A380X

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes

- Refactored Throttle Calibrationto support A380X
- Fixes throttle calibration and adds throttle events for all throttle axis in the A380X
- Added throttle lever sounds to sound.xml for throttles 3 + 4

- [ ] Remember to also update Localazy!

Discord username (if different from GitHub): cdr_maverick

## Additional Information

This required some refactoring of the existing A32NX calibration which was not intended to be used with 4 axis and throttles. 
Overall this is just a refactor and not very clean in all places. It could use a full refactor so it is easier configurable for the A32NX and A380X.

## Screenshots
To make it clearer which axis nees to be mapped to which throttle the axis header now states for which throttle it is used. 
image
image
image

Example MSFS Mapping for 2 axis mapped to 4 throttles - throttle 1+2 use one axis, 3+4 the other
image

## Testing instructions

General:
- Use Reset To Default and delete the ThrottleConfiguration.ini between tests
- if using less axis then throttles use the following MSFS Controller mapping:
    - A320: 1 axis 2 throttles --> map axis 1 to both throttles (or to the general throttle axis) 
    - A320: 2 axis 2 throttles --> map axis 1 to throttle 1, axis 2 to throttle 2
    - A380: 1 axis 4 throttles --> map axis 1 to all 4 throttles (or to the general throttle axis)
    - A380: 2 axis 4 throttles --> map axis 1 to throttle 1 and 2, map axis 2 to throttle 3 and 4
    - A380: 4 axis 4 throttles --> map axis 1 to throttle 1, 2 to 2, etc.
    
A32NX:
- Calibrate with 1 and 2 axis / reverser on axis or not on axis
- Test Load and Save
- Check the ThrottleConfiguration.ini if it makes sense with your configuration
- 
A380X:
- Calibrate your throttles in the A380X with 1 axis, 2 axis and 4 axis
- Test Load and Save
- Check the ThrottleConfiguration.ini if it makes sense with your configuration

Both: 
- Also check standard throttle events for all 4 axis (e.g. THROTTLE_50, or THROTTLE_SET=-16384..16384, ...) if you have them means (SPAD.neXt, AaO, Mobiflight, etc.)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by alexr4339** [comment]
Quality Assurance Tester Report

Discord          : Alex R
Object of testing: #8409
Tier of Testing  : 1
Date             : 13.01.2024

Testing Process: 
Removed all FlyByWire related folders under AppData/Roaming to ensure ThrottleConfig is not present. Downloaded as described.
Loaded the aircraft on the runway and opened the tablet throttle config page. I do have 2 HW axis, in MSFS HW axis one is bound to throttle axis 1+2 while HW axis to is bound to 3+4
Note: HW axis refers to the physical hardware axis, while throttle axis refers to the In-Sim thrust lever position

Negatives:       
Calibrating using the 2 axis option doesnt work. If using the 2 axis option it actually only calibrates throttle axis 1+2. Havent tested 1 axis option yet but I'd assume this option would only calibrate throttle axis 1. Using the 4 axis option however calibrates all 4 throttle axis correctly

Testing Results: 
Not Passed

Conclusions: 
Needs further adjustments for 2 axis and possibly 1 axis calibration option

**Comment by johnpmaguire** [comment]
Quality Assurance Report Trainee
Discord john P Maguire#9027
Object of testing: #8409
Tier of Testing:1
Date: 16/01/2023

Testing Process:
Spawned onto stand and powered up A32NX using ground power. Reset calibration to defaults on first use and for each subsequent calibration. 

An X52 was used with two axis mapped to the same throttle. This was calibrated with reverse on axis to off and independent axis to 1.  The settings were easy and accurate to set up. The cockpit throttle operated as expected. New calibrations with a button to hold reverser. Then toggle reverse and finally to have reverse on axis to on. No issues were identified with reading, setting or using the calibration page. 

 A honeycomb Bravo was connected, and a basic calibration was set up with only throttle 1 and 2 axis being mapped. Then calibrated with reverse on axis to off and independent axis to 2. Each throttle position is slightly different on my Bravo and the setup adjustment worked reading each value independently as necessary to get an accurate calibration using the 3d printed detents.  

Further testing was done with the Bravo including following the documentation for setting up the Bravo. It is overly complex and convoluted to simulate a reserver, but it worked as shown in the docs. Finally, my own setup with reverse on axis and independent axis with an additional detent for idle on the 3D printed detents at -0.4. This works as previously providing a fully functional and smooth reverse at the expense of a slightly shorter travel between idle and climb. 

Negatives
Not directly related. The documentation will need to be updated to more accurately represent the state of the EFB. 

Testing Results
Passed. 

Conclusions 
No regressions for the A32NX. I could set up both the X52 and Bravo.

**Comment by tracernz** [comment]
The label should be "Independent Axes" (plural) rather than "Independent Axis" (singular).

**Comment by frankkopp** [comment]
> The label should be "Independent Axes" (plural) rather than "Independent Axis" (singular).

AH ... didn't even know - will fix ;)
 
> Side question: how do we handle axes 1 and 4 for reverser, since they don't have reverse thrust?

This doesn't need a lot of special treatment - the UI will not allow to set detents and roughly speaking when activated on 1+4 it will simply be ignored (they do have default values for reverser but the engines will simply not use these values)
image

**Comment by KOWA380** [comment]
Quality Assurance Trainee Report

Discord : KOWALSKI#7268
Object of testing: https://github.com/flybywiresim/aircraft/pull/8409
Tier of Testing : (1)
Date : 18/01/2024

Testing Process:

Testing Device: Logitech Extreme 3D
A320: 1 axis 2 throttles --> map axis 1 to both throttles (or to the general throttle axis)

   1.Delete ThrottleConfiguration.ini

   2. Log into Game

   3. Launch aircraft at gate with engines off

   4. Supply External Power and turn on Fly-Pad

   5. Go to throttle configurator in the Fly-Pad

   6. Calibrate for detents

   7. Test Save and Apply 
   
   8. Test Load from file

   9. Check the newly created ThrottleConfiguration.ini if it makes sense with the configuration

Negatives:
N/A

Conclusions:
Throttle detent values shown on Fly-Pad matched with the Values in ThrottleConfiguration.ini and Load and Save worked as it should.

Testing Result: Passed

Media:
Idle detent
[Screenshot 2024-01-18 205610](https://github.com/flybywiresim/aircraft/assets/156888172/8334f13d-676c-4bc1-9432-a588b31e09f9)

CLB
[Screenshot 2024-01-18 205601](https://github.com/flybywiresim/aircraft/assets/156888172/6e9846d4-ac7a-4d84-ac73-4e4c979e128f)

FLEX
[Screenshot 2024-01-18 205552](https://github.com/flybywiresim/aircraft/assets/156888172/d6740595-3bc7-4c70-8242-9a9a7a3183c8)

ThrottleConfiguration.ini values
[Screenshot 2024-01-18 205400](https://github.com/flybywiresim/aircraft/assets/156888172/81e2a06f-2ca6-44a9-a985-344bb17f70fc)

Additional note: Fly-Pad Rounds of the ThrottleConfiguration.ini values

**Comment by frankkopp** [comment]
@KOWA380 thanks for the test - looks good now for the A32NX.

**Pull request merged**
