### PR TITLE
Changed FAULT light to amber

### PR DESCRIPTION
**Pull request by ninjomcs**

### CODE REVIEW

**Comment by ninjomcs** [comment]
^ works at night for me.

**Comment by aboodilatif** [comment]
happened the first time i loaded in, but after re-loading the aircraft they turned back to their original colours. I wasnt able to re-create the white textures after that

**Comment by noga-aviator** [comment]
ok, so it's a first load issue ?

**Comment by michaeldiguiseppi** [comment]
Mine loads up just fine on the first load, with all correct colors (including the amber fault light)

**Comment by ninjomcs** [comment]
That's interesting, wonder why it's inconsistent..

**Comment by tyler58546** [comment]
@ninjomcs how did you export the dds file?

**Comment by ninjomcs** [comment]
I just used paint.net to quickly change the color, and used the default settings: https://gyazo.com/e9eec38eb476522f66c621f774d620d2

**Pull request merged**
