### PR TITLE
fix: inhibit PACKS indication when FADECS are off

### LINKED ISSUE #8313: PACKS show when TOGA even if the FADEC is off
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-11-14T18:44:31+00:00",
    "ref": "refs/heads/master",
    "sha": "72a6813c7abcb600a0d7209e67fb2a6c7e68f677",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "master:72a6813c",
    "version": "v0.12.0-dev.72a6813"
}
```

### Describe the bug

The PACKS indicator on the upper ECAM displays when throttles on TOGA even though both FADECS are off.

 image

### Expected behavior

The indicator should not be visible as the signal to the EEC is lost. 

### Steps to reproduce

1. Spawn the aircraft in C&D
2. Move throttles to TOGA, observe PACKS display on upper ecam
3. Wait 5 minutes for both FADEC to de-energize 
4. Repeat step 2

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

alepouna

### PR DESCRIPTION
**Pull request by ArtemisPlayer**
Fixes #8313

## Summary of Changes
I added a few lines of code to check that FADECS are on to prevent displaying the PACKS indication when they are off.

## References
The behavior of the PACKS indication is given here: [https://www.aviationhunt.com/a320-ecam-engine-warning-display/](https://www.aviationhunt.com/a320-ecam-engine-warning-display/)

## Additional context
First issue.
Discord username: artemisplayer

## Testing instructions
Start the APU from C&D, check that when FADECS are off, and throttle to TOGA (or FLX) no PACKS indication appears on the upper ECAM. Check that the indication appears once the FADECS are running and the throttle is on FLX or TOGA.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ArtemisPlayer** [comment]
Do not merge please, it looks like there is a bug, I am investigating.

**Comment by auroraisluna** [comment]
Is this good to QA? Seems like it needs workflow approval

**Comment by ArtemisPlayer** [comment]
The error is: 
```
---- hydraulic::tests::a380_hydraulics::brake_logic_green_backup_emergency stdout ----
thread 'hydraulic::tests::a380_hydraulics::brake_logic_green_backup_emergency' panicked at 'assertion failed: test_bed.get_brake_left_green_pressure() < Pressure::new::<psi>(50.)', fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs:9500:13
```
so I think that is not related to this PR. Can we be sure that the master branch does pass all the checks ?

**Comment by kohenen** [comment]
Can you elaborate this instruction "Start the APU from C&D, check that when FADECS are off, and throttle to TOGA (or FLX) no PACKS indication appears on the upper ECAM"

How to check the FADECS are off?

**Pull request merged**
