### PR TITLE
feat(a380x/lights): add cockpit ambient bounce lights

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Summary of Changes

Adds soft and wide bounce lights to the cockpit ambient lights to make the cockpit more realistically lit.

## Screenshots (if necessary)

**OVERHEAD BEFORE/AFTER:**
image
image

**COCKPIT FRONT BEFORE/AFTER:**

image
image

**COCKPIT BACK BEFORE/AFTER:**

image
image

All pics are taken at full ambient knob setting and with the cabin disabled. And the light color is currently on the warmer side as I kept it the same as the source lights. Since lights will change a lot in MSFS24 further tunning will probably be done for that sim.

## Additional context

Discord username (if different from GitHub):

## Testing instructions
NOTE: Currently there are some cabin light leaks that are tied to the cockpit ambient light switch, that help make the cockpit brighter, you should disable the cabin when comparing to current master to make a more accurate comparison with it. But please test with all plausible configurations.

Needs [776b090](https://github.com/flybywiresim/aircraft-large-files/commit/776b09063e35bdab0b47850af685b1f271df5fc5) this commit or above from the large-files repo to function properly, as it uses a new light effect.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Comment by C-Schaffhausen** [comment]
I feel like it's a bit too much, never seen a cockpit this bright before. Could you show how it looks at half brightness?

**Comment by ImenesFBW** [comment]
> I feel like it's a bit too much, never seen a cockpit this bright before. Could you show how it looks at half brightness?
This is at half.
image

If you have some personal reference photos, or you are able to grab some at different ambient light settings in the cockpit, please send them over, will happily take a look.

**Comment by Pruznak** [comment]
I like it much more at half, I fell like it looks too artificial at full brightness.

**Comment by ImenesFBW** [comment]
> I like it much more at half, I fell like it looks too artificial at full brightness.

I doubt that the knob is set at full setting very often, using the storm light will put it at max. One of the reasons I want to include this before working on the storm light.

**Comment by Texagg12** [comment]
If I may add a comment as one of the verified pilots on here. The idea of the storm light is to make it where if you need instant daylight inside the cockpit you get it. Therefore, I'd say from the examples above it looks good. There is a dim-able knob as not to shock the senses but that is not what the storm does.

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord Username: 2cas
Object of testing: #9442
Aircraft: A380X 
Tier of Testing: 1
Date: 14/11/2024 

Testing Process: 
 
- [x] Spawned and adjusted ambient light knob -> Light did not work as elec is not supplied
- [x] Connected EXT PWR, adjusted ambient light -> observed ambient light as per the screenshots
- [x] After engine start - Light remains working

Testing Results: 
QA Passed  

Negatives:       

- N/A

Conclusions: 

LGTM

**Pull request merged**
