### PR TITLE
fix(a32nx): update for GSX config

### PR DESCRIPTION
**Pull request by Watsi01**
## Summary of Changes
These are some fixes and additions for the GSX config file for the A32NX.

1.  added contact points for the water and lavatory hose (water and lavatory trucks added with GSX version 3.1.5)
2.  removed emergency exit (falsly assigned as a passenger door in the last update, 1 year ago). Until we have more animated doors, still only 1L (pax) and 4R (catering) is accessible.
3.  changed baggage loader to container loader - with the correct container type for the A320 (AKH)
4.  added ceiling definitions (mandatory since some updates ago)

## Screenshots (if necessary)
no

## References
no

Discord username (if different from GitHub): RogePete

## Testing instructions
For GSX users only:

-  Check if the water and lavatory hose are connecting at the aircraft (and not in the air).
-  Check if (correct) containers are used for cargo loading
-  Check if everything else works like before

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Review by alepouna — APPROVED** [review]

**Comment by 2hwk** [comment]
Needs Changelog.md entry

**Comment by Watsi01** [comment]
> Needs Changelog.md entry

Had strange conflict issues with changelog. So I keep it default and add changelog when merge.

**Comment by Maximilian-Reuter** [comment]
> > Needs Changelog.md entry
> 
> Had strange conflict issues with changelog. So I keep it default and add changelog when merge.

well yeah it conflicts every time a PR gets merged that changes the changelog. shouldnt be a difficult confilct to fix though

**Comment by tracernz** [comment]
Needs 0.13 changelog.

**Comment by frenchairbuspilot** [comment]
QA Trainee Pilot Report

Discord          : jp320
Object of testing: #8927 
Tier of Testing  : 1
Date             : 30/10/2024

Testing Process: 
Loaded in EBBR gate 150
asked for water and waste then refuelling and boarding then pushback

Negatives:
On the first attempt the loading belt didn't show up as i only requested boarding and not deboarding first. But after a quick GSX reset everything worked as intended

Testing Results: 
Passed

Conclusions: 
Working as expected

Media:
Capture d’écran 2024-10-30 215200
Capture d’écran 2024-10-30 215538
Capture d’écran 2024-10-30 220100

**Pull request merged**
