### PR TITLE
fix(a380x/eng): XML fix for thrust levers

### LINKED ISSUE #8886: THR levers issues
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-07T19:25:01+00:00",
    "ref": "refs/heads/a380x-experimental",
    "sha": "02f7264f43a503cf13e4dbe77c9d2ea3c44f1d6c",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "a380x-experimental:02f7264f",
    "version": "a380x-v0.12.0-a380x-experimental.02f7264"
}
```

### Describe the bug

1. THR lever detents position do not match cockpit decals
2. Mouse-dragging THR lever 1 or 4 activates reverse thrust (visible in E/WD, sounds and taxi speed)

### Expected behavior

1. Detents matching decals
2. Reverse thurst not being possible in eng 1 and 4

### Steps to reproduce

1. move THR levers and check detent positions vs cockpit decals
2. mouse-drag eng 1 and 4 into reverse

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Bernardo R

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #8886 

## Summary of Changes

- Fixes detent TLAs to match decals in 3D model
- Fix drag XML code so thrust levers can be dragged again (disabling reverser in the meantime, don't know how to get that to work, and I can't figure it out)
- Fix detent sounds

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Verify that thrust lever detents matches the decals in the 3D model
2. Verify that thrust lever detent clicks (i.e. sounds) are still audible as expected
3. Verify that dragging the thrust levers modifies the thrust setting (reversers don't work)
4. Verify that HW throttles, and F1-F4 key control still works for the throttle

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by becas22** [comment]
Quality Assurance Report

Discord Username  : bernardor96 
Object of testing : #9004 
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 02/10/2024

Testing Process: 
Verify that thrust lever detents matches the decals in the 3D model
Verify that thrust lever detent clicks (i.e. sounds) are still audible as expected
Verify that dragging the thrust levers modifies the thrust setting (reversers don't work)
Verify that HW throttles, and F1-F4 key control still works for the throttle 

Testing Results: 
Passed  

Negatives:       
There's a little sound when exiting out of idle which I don't think exists IRL

Conclusions: 
Marking it as passed because of very minor negative and much better behaviour overall

**Comment by flogross89** [comment]
> Quality Assurance Report
> 
> Discord Username : bernardor96 Object of testing : #9004 Aircraft : A380X Tier of Testing : 1 Date : 02/10/2024
> 
> Testing Process: Verify that thrust lever detents matches the decals in the 3D model Verify that thrust lever detent clicks (i.e. sounds) are still audible as expected Verify that dragging the thrust levers modifies the thrust setting (reversers don't work) Verify that HW throttles, and F1-F4 key control still works for the throttle
> 
> Testing Results: Passed
> 
> Negatives: There's a little sound when exiting out of idle which I don't think exists IRL
> 
> Conclusions: Marking it as passed because of very minor negative and much better behaviour overall

Thanks for the test! I oversaw one thrust lever, it still made a sound when passing 23% angle. Isn't there a sound when the thrust levers push against the "lower end", where idle thrust is on the A380? In our file it's a different sound called "IdleDetent", but it sounds similar to a detent. 

We could either leave the IdleDetent sound in or remove it altogether, however then there would be no audible feedback of putting the TL to idle. What do you think?

**Comment by becas22** [comment]
When you push them to idle the sound is there and I think it should remain

**Comment by flogross89** [comment]
> When you push them to idle the sound is there and I think it should remain

Alright, let's keep that sound then. Did you test the latest build yet? Shouldn't have the sound at 25% anymore.

**Comment by becas22** [comment]
> Alright, let's keep that sound then. Did you test the latest build yet? Shouldn't have the sound at 25% anymore.

I did. No negatives now! Need a full QA report again?

**Comment by flogross89** [comment]
> > Alright, let's keep that sound then. Did you test the latest build yet? Shouldn't have the sound at 25% anymore.
> 
> I did. No negatives now! Need a full QA report again?

No need, thanks! Will merge now

**Pull request merged**
