### PR TITLE
ci: Rename workflows from 'PR' to more descriptive names 

### PR DESCRIPTION
**Pull request by alepouna**
## Summary of Changes

1. Renames the PR action for building the aircraft from 'PR' to 'PR Build' (as well as the file name) so that it is more easily locatable as some PRs may have multiple actions run under the 'PR' label, making it slightly frustrating to find the right build, especially for the QA team. This also improves visibility for working with the repository. 
This PR also updates the 'PR template text' for the new label. 

2. Renames the PR semantic titles action from 'PR' to 'PR Semantics' (as well as the file name) so that it is more identifiable in the checks tab and when working with the repository. 

## Additional context

Discord username (if different from GitHub):

## Testing instructions

No QA needed. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
PR Build is badly named as it also includes lint and tests

**Comment by Benjozork** [comment]
IMO The current names didn't pose problems, I don't believe they need to change

**Comment by alepouna** [comment]
> PR Build is badly named as it also includes lint and tests

Any recommendations? I thought initially of naming it "PR Tests & Build".

**Comment by Benjozork** [comment]
I'd just do `PR` and `PR Semantics`.

**Comment by alepouna** [comment]
> IMO The current names didn't pose problems, I don't believe they need to change

There are some PRs that look like this: 
image

Which was the motivation for this (along side a comment by a QA member that couldn't find the artifact files, and I've personally suffered this in the past when starting QA)

**Comment by 2hwk** [comment]
> > PR Build is badly named as it also includes lint and tests
> 
> Any recommendations? I thought initially of naming it "PR Tests & Build".

Yes maybe tests and build would be better

**Pull request merged**
