### PR TITLE
fix(fm): don't update T-P position if we aren't inserting a direct to

### LINKED ISSUE #8968: fms: t-p shifts when flightplan revised
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

DIR TO a waypoint, and insert a hold there. Each time you revise the hold, the T-P shown on the ND shift to PPOS.
image

### Expected behavior

T-P should not move unless a new DIR TO is performed.

### Steps to reproduce

1. DIR TO a waypoint, and insert a hold there.
2. Revise the hold.
3. Observe T-P holds when you execute the revision.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by Benjozork**
Fixes #8968

## Summary of Changes

- Don't update T-P position if we aren't inserting a direct to
- Make T-P position update properly edit the definition so that it works with sync

## Testing instructions

- Make sure T-P updates when inserting a direct to
  - Wait a minute until confirming a direct to to a far away waypoint - make sure the T-P point moves to the airplane position when inserting
 - Make sure T-P does not move when it is the FROM leg and making another modification that creates a temporary plan, for example, adding a hold somewhere
   - Confirm the direct to, then make the unrelated modification a few moments after (so you can notice whether the T-P moves or not)

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by tracernz** [comment]
Discord Username : tracernz
Object of testing : https://github.com/flybywiresim/aircraft/pull/8974
Aircraft : A32NX
Tier of Testing : 1
Date : 23/09/2024

Testing Process:
First tested the 2nd case per the original repro: ✅ 
Then tested the first case: T-P is updated once when the new DIR TO first creates a TMPY (this one should not be shown on the ND!), and doesn't update again so the dashed path doesn't move with the plane as it should. It also did not update when inserted.❌ 

Testing Results:
Failed

Media:
image
image

**Comment by tracernz** [comment]
Needs 0.13 changelog.

**Comment by frenchairbuspilot** [comment]
QA Trainee Pilot Report

Discord          : jp320
Object of testing: #8974 
Tier of Testing  : 1
Date             : 31/10/2024
Testing Process: 
Loaded CDG BRU, After take off, first DIR TO GSY which isn't on the route, T-P remains behind the aircraft but after a minute when direct to is entered, T-P updates to aircraft position. No effect on the rest of the routing in the Fpln page.

After a while DCT TO RODRI, a wpt on the arrival, T-P again stays behind the aircraft and is not updated to aircraft position whilst kept in temporary FPLN, but when entered after  a minute or two, T-P displayed behind the aircraft at the point where the DIR TO was selected. No effect on the rest of the routing,

Negatives:
T-P no updated to aircraft position when temporary FPLN displayed.
After the first DIR TO, all T-P when DIR TO entered, remains behind the aircraft rather than beeing updated to present pos.

Testing Results: 
Not Passed


Media:
Selected DIR TO GSY updated to T-P to current position. 
Capture d’écran 2024-10-31 105811

Then DIR TO RODRI, T-P stays behind the aircraft
Capture d’écran 2024-10-31 105849

After the DIR TO inserted, T-P not updated to current position
Capture d’écran 2024-10-31 105928

Same thing for GTQ  , not on the route but T-P remains behind the aircraft
Capture d’écran 2024-10-31 103852
Capture d’écran 2024-10-31 103937

**Comment by nebj00la** [comment]
Quality Assurance Trainee Report

Discord Username  : nebj00la
Object of testing : #8974
Aircraft          : A32NX
Tier of Testing   : 1
Date              : 08/11/2024

Testing Process: 

1. Loaded various waypoints for approach to KPVD.
2. Set DIR TO directly after airplane spawn at 5000FT, making sure T-P updated to current position after insert.
3. Waited to make another DIR TO for about a minute in draft form, then INSERT brought T-P to current airplane position.
4. Waited until the airplane reached a waypoint set as a DIR TO, set a HOLD pattern at a waypoint between current and destination airport, T-P did not move.
5. Inserted HOLD, then made an unrelated DIR TO another waypoint and noticed the T-P moved to the appropriate position.

Testing Results: 

Passed

Media:

**Comment by tracernz** [comment]
- The T-P is not updating while the DIR TO preview is active (**incorrect**).
  image
- It does update when the DIR TO is activated (correct).
  image
- The old T-P remains when I preview a new DIR TO and cancel it (correct).
- Leaving the DIR TO page with a pending DIR TO does not erase it (incorrect and out of scope for this PR).
- The T-P remains fixed, but the DF leg tries to update in the TMPY when I make an edit further along the plan (**incorrect**):
  image

**Comment by tracernz** [comment]
Alright, we discussed it and the DIR TO preview not updating is a regression with fms-v2 but out of scope for this PR.

**Comment by 2hwk** [comment]
Needs Changelog still before merge ^

**Pull request merged**
