### PR TITLE
feat(a380/pfd): FMA code cleanup & update possible fmas

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #[issue_no]

## Summary of Changes

Cleanup reference to FINAL APP in PFD FMA file as it doesn't exist on the A380. 
Updates possible FMA list with OP CLB blue, RWY blue, RWY + NAV blue, ALT CRZ * & ALT CRZ blue 
(These are not hooked to anything as it require implementation on the simulink model).
## Screenshots (if necessary)

FMA2
FMA1
ALT CRZ

## References

image
image
image
image

## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

1) Regression test: Perform a flight and verify the FMA modes still work as before, more specifically, armed vertical & lateral modes alongside ALT*. Note: The modes in the screenshot (ALT CRZ * ALT CRZ Blue Open Climb blue & runway blue) are not supposed to work.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Comment by beheh** [comment]
Are you sure ALT CRZ can be armed/ALT CRZ* can be engaged I thought it was ALT blue, ALT*, and then it turns into ALT CRZ. Maybe check with one of our autoflight gurus such as @lukecologne.

**Comment by BravoMike99** [comment]
> Are you sure ALT CRZ can be armed/ALT CRZ* can be engaged I thought it was ALT blue, ALT*, and then it turns into ALT CRZ. Maybe check with one of our autoflight gurus such as @lukecologne.

Yes, since the A330 it can.
image
image

**Review by 2hwk — APPROVED** [review]

**Comment by alexr4339** [comment]
Quality Assurance Tester

Discord Username  : alexdnzdmb
Object of testing : #9501 
Aircraft          : A380X
Tier of Testing   : 1
Date              : 17/11/2024

Testing Process: 
Initialized LPPT to LPPT with a SID and approach. Flight level for that flight was defined as FL080 in the FMS. Departed, did a direct to PT718 (or similar) and checked FMA. When interecepting FL080, ALT CRZ* should have triggered but didnt. When being on FL080, ALT CRZ triggered.

image
image

Testing Results: 
Not Passed

Negatives:       


Conclusions: 


Media:

**Comment by beheh** [comment]
@alexr4339 Please carefully re-read the testing instructions. This is a regression test only, the new modes are not hooked up to anything yet.

**Comment by beheh** [comment]
Ah, great 👍

**Pull request merged**
