### PR TITLE
fix(a380x/engine): Correct throttle number typo

### PR DESCRIPTION
**Pull request by rthom91**
4 engines, not 5. ;)

### CODE REVIEW

**Review by Gurgel100 — APPROVED** [review]
Nice catch. Thank you.

**Comment by Gurgel100** [comment]
Please add a changelog entry

**Comment by rthom91** [comment]
> Please add a changelog entry

Added

**Comment by Gurgel100** [comment]
Testing instructions:
Make a full flight in the A380x and check if everything works as expected (especially that the T.O. MEMO, T.O. INHIBIT, and LANDING MEMO are shown in the ECAM).

**Comment by 2hwk** [comment]
Quality Assurance Tester Report

Discord Username: 2cas
Object of testing: #9493
Aircraft:  A380X
Tier of Testing: 1
Date: 15/11/2024 

Testing Process: 
- [x] Make a full flight in the A380x and check if everything works as expected (especially that the T.O. MEMO, T.O. INHIBIT, and LANDING MEMO are shown in the ECAM).

Testing Results: 
QA Passed

Negatives:       
- N/A

Conclusions: 
- LGTM

**Comment by Gurgel100** [comment]
Please resolve conflicts.

**Pull request merged**
