### PR TITLE
feat(athr/fadec): improved reverse thrust limit based on TOGA limit

### LINKED ISSUE #7967: [Engines/EWD] - Negative Thrust limit value when toggling reverse thrust
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-14T14:28:11+00:00",
    "ref": "refs/heads/experimental",
    "sha": "49faa5cb317e1fa71bfa29cd18157dd2735b733c",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:49faa5cb",
    "version": "v0.10.0-exp.49faa5c"
}
```

### Describe the bug

Upon toggling reverse thrust, the thrust limit value becomes negative on the EWD.
MRev

### Expected behavior

Thrust limit value to be positive

### Steps to reproduce

1) Toggle reverse thrust (can be with engines on or off)
2) Observe the thrust limit value on the top right of the EWD.

### References (optional)

E.g. : https://youtu.be/UQE-g7yrY3w?t=105

### Additional info (optional)

_No response_

### Discord Username (optional)

Bruno_pt99#5802

### PR DESCRIPTION
**Pull request by aguther**
Fixes #7967

## Summary of Changes
This PR introduces an improved reverse thrust limit instead of the constant 45% N1 in the past. Right now, the reverse thrust limit is calculated in a percentage of the TOGA limit.

## Testing instructions
- test reverse thrust in different situations and environmental conditions; expectation is that N1 from the shown N1 limit can be achieved
- test that no excessive negative speed can be achieved with reverse thrust

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Needs testing instructions before QA is ready to go

**Comment by 2hwk** [comment]
@aguther Just need instructions for tester and we can set this as ready to test

**Comment by noonebling** [comment]
Discord          : noonebling
Object of testing: 8565
Tier of Testing  : 1
Date             : 07/04/2024

Testing Process: 
Tested reverse thrust in different situations and environmental conditions. 

Negatives:
N/A

Testing Results: 
Passed

Conclusions: 
Works as expected

**Comment by 2hwk** [comment]
QA pass label removed due to some late changes that require re-testing, also would like to see more QA trainees be able to run through this one while we wait for some large PR merges.

**Comment by donstim** [comment]
> QA pass label removed due to some late changes that require re-testing, also would like to see more QA trainees be able to run through this one while we wait for some large PR merges.

What else is needed now to merge this?

**Comment by aguther** [comment]
From my side it's ready to go after a short test.

**Pull request merged**
