### PR TITLE
refactor: Fadec rewrite using Cpp framework (2nd)

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes
Migration of the current fadec code for the A32NX and A380X to the cpp framework with cleanup and additional commenting for better understanding and maintainability.  

No change in logic and also not further modularized into shared and specific parts as most of the A380X fadec code still uses the A32NX polynomials and tables. As this will surely change any further sharing of code should be done after when it is clear which parts of the code are really sharable. 

Performance has improved a little as reading and writing of data from/to the sim has been optimized. 

Discord username (if different from GitHub): cdr_maverick

## Testing instructions
Full regression tests on the A32NX with full flights from c&d, runway and the air. 
Also fuel handling (fueling, saving and loading of fuel per ATC ID) needs to be tested. 

Things to look out for:
- unusual thrust limits in the EWD
- unusual commanded
- unusual values or engine behaviour
- FLX to CLB transistion (or other transisitons - but this is the critical one)
- VNAV issues (e.g. incorrect times) in the flight plan after vnav calculations
- any other possible situations where engine thrust and the use of data from the engine might be relevant (e.g. VNAV)

Same for the A380X but to a lesser extend as the fadec code is unfinished anyway. 
As on the fuel page in the A380X the order of the tanks changed please also test and look at this.  

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
I've review the new changes (LGTM) and otherwise relying on the previous reviews. Good to go QA 👍 .

**Comment by frankkopp** [comment]
> I've review the new changes (LGTM) and otherwise relying on the previous reviews. Good to go QA 👍 .

Thanks - I'll update the test instruction to be more clear what should be tested.

**Comment by Watsi01** [comment]
Non_QA Tester:

Did a full flight (EDDH-EDDM with full FMS programming)

- Alt and speed calculation (FLP page) works now. 
- ETA and EFOB calculation works again.
- Manipulating/deleting constraints works (calculation updates accordingly).
- FLX works - correct %N1 when having a flx temp.
- Throttle works again (there shall be thrust) 
- Graduate increase of thrust when going to CLB mode (having a low flx takeoff thrust) works.
- TOC and TOD calc works


Everything looks good.

Passed!

**Comment by Saschl** [comment]
Quality Assurance Report

Discord : saschl
Object of testing: https://github.com/flybywiresim/aircraft/pull/8622
Tier of Testing : 2
Date : 15.04.2024

Testing Process:


Full flight EDDS - LIRQ:

Engine start/shutdown working as expected.
FLX thrust working as expected and showing reasonable values.
VNAV calculations were reasonable.

Conducted takeoffs with FLX and TOGA, no issues found.
Observed transition from FLX to CLB phase. Thrust increase happens gradually, no issues found.

Checked if fuel is loaded and persisted properly when starting C&D. Could not see issues.

Negatives:
N/A

Testing Results:
Passed

Conclusions:
Working as expected

Media:

Screenshot 2024-04-15 105906




https://github.com/flybywiresim/aircraft/assets/19493808/682e0b30-264e-4184-87a9-4ae17b6c3cb7

**Pull request merged**
