### PR TITLE
feat(ap): add NAV on GA

### PR DESCRIPTION
**Pull request by lukecologne**
## Summary of Changes

This PR adds the capability to remain in or enter NAV mode when initiating a goaround. This is not yet particularly useful, but will be once fms-v2 is merged with the capability of goaround procedures.

Now, when entering SRS GA, NAV will be engaged if possible, otherwise NAV will be armed if possible and GA TRK will be engaged, except if the lateral mode already was HDG, then HDG remains engaged. If TRK/FPA was active, it will revert to HDG/VS.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — CHANGES_REQUESTED** [review]
Seems worthy of changelog.md update

**Review by 2hwk — APPROVED** [review]

**Comment by flogross89** [comment]
Does it make sense to also implement that on the A380? As it's based on fms-v2 as well

**Comment by lukecologne** [comment]
I don't see why not

**Review by aguther — APPROVED** [review]
LGTM

**Comment by flogross89** [comment]
> I don't see why not

thank you!

**Pull request merged**
