### PR TITLE
fix: keep flight number set even if already taken

### LINKED ISSUE #8650: INIT Page: field 'FLT NBR' not populated by Simbrief, and cannot be entered manually
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-04-27T16:40:29+00:00",
    "ref": "refs/heads/master",
    "sha": "7518ab0c54b296f4cb774519889171ed7d8b4df5",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:7518ab0c",
    "version": "a32nx-v0.12.0-dev.7518ab0"
}
```

### Describe the bug

On the INIT page, the FLT NBR field is neither populated after initializing from a Simbrief plan, nor can it be manually entered.
Note that on the INIT/REVIEW page, the Flt Nbr is correct.

### Expected behavior

FLT NBR should be

1. populated as defined in the Simbrief flight plan
2. AND it should be possible to manually modify it

### Steps to reproduce

1. Create a Simbrief flight plan, e.g. EDDS to EHAM. Make sure to include an ATC Callsign (I used DLH2NB).
2. Start C/D on any stand in your departure airport
3. On the MCDU, go MCDU MENU > ATSU > AOC MENU > INIT/PRES
4. Click INIT DATA REQ -> all is OK. Note the correct Flight Number in the top left corner
5. Go to page INIT
6. Load the flight plan 
-> BUG 1: note that the FLT NBR remains empty 
7. Enter a flight number manually (e.g. DLH2NB) in the scratchpad, and then click the corresponding line key 
-> BUG 2: the value is not accepted, no error message displayed

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

StephN-B

### PR DESCRIPTION
**Pull request by BenJuan26**
Fixes #8650

## Summary of Changes

Set the flight number in the FMC and the ATSU regardless of whether it's already taken. This has the benefit of setting the flight number instantly, instead of waiting to hear back from the API. The check is still made, and if the flight number is taken, the `FLT NBR IN USE` message is received and displayed by the ATSU.

Not yet tested: the effect of having a duplicate flight number during TELEX operations.

## Screenshots (if necessary)

Starting the init req from the FCU. Note that no message is displayed in the FCU. A received message can be seen in the ATSU. The `FLT NBR IN USE` message is in the scratchpad, and the flight number is populated in the AOC.

https://github.com/flybywiresim/aircraft/assets/4079548/af4e2326-116d-4df6-9aae-282bb6b19972

I don't know if this is expected, but starting the request from the ATSU does not populate anything in the FCU, unlike the reverse.

https://github.com/flybywiresim/aircraft/assets/4079548/f88d5dad-3e0f-48f5-893c-babf784cc857

Not necessarily related to this PR, but since it was brought up, I can confirm that the ATSU is reset completely after a flight is completed, including the flight number.

https://github.com/flybywiresim/aircraft/assets/4079548/7a51fa14-bea6-4e43-9929-a1755e2c30c3

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by LunakisDev** [comment]
Quality Assurance Trainee Report

Discord: LunakisLeaks
Object of testing: #8656
Tier of Testing: 1
Date: 29/6/2024

Testing Process:
1. Spawned at LCLK.
2. Init Req
3. Verified that the FLT NBR is set in the INIT page + PROG.
4. Verified that the "FLT NBR IN USE" message is received and displayed by the ATSU.

Negatives:
N/A

Testing Results:
Passed

Conclusions:
LGTM

**Comment by tracernz** [comment]
Needs 0.13 changelog.

**Comment by BenJuan26** [comment]
[Some context from Discord](https://discord.com/channels/738864299392630914/754130199804772372/1256939111944687758) since it was never captured here:

> `@ExampleWasTaken`:
> 
> I'm a bit sceptical towards https://github.com/flybywiresim/aircraft/pull/8656.
> 
> At the moment this seems a bit rushed imo. Both hoppie and TELEX rely on the flight number. So allowing the same flight number to exist might have implications on those features. I've seen Lunakis' test on the map and I'm aware that there are no testing instructions yet but I just wanted to share my humble opinion. Perhaps this feature isn't even ready for testing yet and this discussion premature.
> 
> I'm generally a fan of this feature, however, I think that there should probably be a `Ignore FLT NBR IN USE` setting in the EFB that automatically disables TELEX and hoppie functionality as to avoid issues with those systems.

I agree with all of this. It's why I hadn't written testing instructions yet -- it wasn't clear to me 1) how TELEX and Hoppie are affected, 2) whether TELEX login failure is sufficient to consider it handled, 3) how to reliably test TELEX and Hoppie in the first place.

Those issues need to be handled/decided before this PR can move forward.

**Comment by tracernz** [comment]
TELEX won't log in, which is fine, and what happened before, and Hoppie has to solve this problem themselves, as even if we stopped 2 FBW planes having the same callsign on Hoppie, any other aircraft could still login with the same callsign as an FBW plane.

**Pull request merged**
