### PR TITLE
feat(CDU): return to previous FPlan position

### LINKED ISSUE #7422: [MCDU] Remember F-Plan scroll on return
### Aircraft Version

Development

### Description

When returning from lateral (LSKnL) or vertical (LSKnR) options from a F-PLAN the MCDU should preserve the right F-PLAN page/scroll. Currently returning from a waypoint using "Return" (LSK6L) to F-PLAN resets the page and shows it from top. If a flight plan has many waypoints, then one has to scroll again to the right page to update the next waypoint.

This scroll position should be preserved also when returning from Departure or Arrival. 
It might be invistigated whether scroll position is preserved when using the F-PLAN button instead of "Return" (LSK6L).

### References (optional)

_Needs references_

### Additional info (optional)

_No response_

### Discord Username (optional)

coolll.sk#0022

### PR DESCRIPTION
**Pull request by vkrizan**
Fixes #7422

## Summary of Changes

The primary aim of the PR is to F-PLAN offset stateful to be able to return back to same scroll.
Offset changes on these situations:
* New Departure insertion -- resets to top
* New Arrival -- resets to bottom
* Airway insertion -- moves by number of inserted waypoints
* New INIT (incl. AOC) -- resests to top
* Second press of FPLAN button -- resets to top

The PR also refactors FlightPlanManager to await flight plan version updates. This is to ensure that a new offset set on waypoint insertions is correct, as it is computed and limited to actual waypoint numbers.

## References

https://youtu.be/syr4G3pokgU?t=191
https://youtu.be/_skUOMfv-AQ
https://youtu.be/E8IjkgQjw2M
https://youtu.be/D7HjVlvKd8o
https://youtu.be/dDny7J9Bc1Y
https://youtu.be/tXnbLtRpcqM

## Additional context

Discord username (if different from GitHub): coolll.sk#0022

## Testing instructions

For FPLAN:
* validate returns from sub pages returning to FPLAN -- scroll should be the same
  * Departure, Arrival ... (with no changes)
  * Vertical and Lateral revision pages
  * Holds
* validate return after insertions from Departure, Arrival, Airways
  * New Departure insertion -- resets to top
  * New Arrival -- resets to bottom
  * Airway insertion -- moves by number of inserted waypoints
* validate second press of FPLAN button -- resets to top
* regression test AIRPORT button 

For the FPM refactoring:
* regression testing with a full flight
* observe INIT from AOC
* observe DIR to behavior
* try waypoint changes during curise

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by 2hwk** [comment]
Just wondering if this is accurate to irl behaviour, shouldn't be hard to find a few videos for this or it can be requested in the pilots channel on discord if nothing is found.

**Comment by vkrizan** [comment]
I'll try to check some videos over the weekend to find references.

**Comment by vkrizan** [comment]
Okay, I've found some reference material, but none of it shows the "Return" or "Erase". However, I've found out that the position/offset of the F-Plan is changing when inserting new airways or arrivals. It seems that it returns into position of first (arival) of last (airway) waypoint that has been inserted. I'll try to find more.

Put into draft until that's resolved.

**Comment by 2hwk** [comment]
> Hi @2hwk, I've looked to some reference video materials. What I could have been able to find are how the FPlan behaves when inserting SID, STAR, Hold and airways. Some of the videos were showing Secondary F-Plan, which I guess should have the same behavior.

> The F-Plan always tries to return to the same position when inserting STAR, waypoint and holds. It is different for Arrivals when it shows next wpt after VIA at top. And for Airways inserts it returns back having the last airway wpt at position 2.

> How it behaves during cruise is unknown. I'm guessing that the behavior is the same, it just has to account for changing waypoint list.

> How we can get more reference materials?

This should be good enough for now, note that only the 3rd/4th video show a honeywell MCDU, thales behaviour may be different.

**Comment by vkrizan** [comment]
I've tested it with a short flight.

It should be easier to improve the offset if there are new references found. One room for improvement is returning to temporary flight plan.

With regards to FPM changes, I can try to help propagate those to fpm-v2.

**Comment by 2hwk** [comment]
> 



> I've tested it with a short flight.
> 
> It should be easier to improve the offset if there are new references found. One room for improvement is returning to temporary flight plan.
> 
> With regards to FPM changes, I can try to help propagate those to fpm-v2.

Yes please do so, I think this PR should be retargeted at the new fms branch, not master. 

Also coordinate any changes in the CDU in the #ata-22-fms channel on discord, we probably would want to include this as a part of that big update than introduced potential conflicts now.

**Comment by vkrizan** [comment]
Hey, sorry for the delay. I've tried to update and rebase it on top of fms-v2, but the branch is unstable.  Rewrite of the `mcdu.flightPlanManager` into a service is still unfinished there. I've kept the fms-v2 rebase separate at my [cdu-remember-fplan-offset-fms-v2](https://github.com/vkrizan/a32nx/tree/cdu-remember-fplan-offset-fms-v2) branch.

I'd prefer to merge this to master, to benefit out of it sooner, if that's possible. I'm gonna reach out on #ata-22-fms channel on discord nevertheless.

Cheers.

**Comment by vkrizan** [comment]
I'm gonna close this, as there would be a new code base that might fix this. If not, then I can try to get back to it.

**Pull request closed without merging**
