### PR TITLE
fix(A380X/PERF): Change managed speeds to more realistic numbers

### PR DESCRIPTION
**Pull request by Slightlyclueless**
Fixes #[issue_no]

## Summary of Changes
Changed the fixed mach in the performance pages to be slightly more realistic values. CLB and DES are .84 and CLB is .85.

## References

[Just Planes Videos](https://www.youtube.com/watch?v=yGlS2QBuX7s)
A380 FCOM

## Additional context

Discord username (if different from GitHub):
abnormaltoast

## Testing instructions

1. On reaching mach conversion ensure that Managed climb is targeting .84
2. When in CRZ ensure that managed cruise is targeting .85
3. On descent ensure that managed descent is targeting .84

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Note changelog format should be <item> - <user>, but the line above yours was incorrect.

**Comment by Awemeter** [comment]
Quality Assurance Trainee Report

Discord Username: Awemeter 
Object of testing: #9322
Aircraft: A380X 
Tier of Testing: 1
Date: 8/11/2024 

Testing Process: 
 
Installed A380 artifact along with stable V0.12.1 and loaded sim
Started flight from EGLL-EHAM
Prior to takeoff ensured perf page showed .84 for climb phase, .85 for cruise, and .84 for descent.
Departed and ensured managed speed above 10k and past mach transition is .84 during climb
Once cruising altitude is reached ensured managed speed is mach .85
During descent ensured managed speed is .84 prior to the transition
Testing Results: 
Passed 

Negatives:       

During cruise the SPD Field is not populated in the FMS when you haven't/won't reach mach transition during your flight. Not sure if this is realistic or not since Im not a A380 pilot.
Conclusions: 

Passed according to PR description and testing instructions but may have potential inaccuracy
Media:

image

**Comment by Slightlyclueless** [comment]
> During cruise the SPD Field is not populated in the FMS when you haven't/won't reach mach transition during your flight. Not sure if this is realistic or not since Im not a A380 pilot.
FWIW the IRL references I can find do not show the SPD above mach transition

image

**Comment by Awemeter** [comment]
> > During cruise the SPD Field is not populated in the FMS when you haven't/won't reach mach transition during your flight. Not sure if this is realistic or not since Im not a A380 pilot.
> 
> 
> 
> FWIW the IRL references I can find do not show the SPD above mach transition
> 
> 
> 
> image
> 
> 

What if your final cruising altitude is below an altitude where you would use Mach? This reference is using a cruise altitude of FL380. What if it's lower?

**Comment by BravoMike99** [comment]
> > > During cruise the SPD Field is not populated in the FMS when you haven't/won't reach mach transition during your flight. Not sure if this is realistic or not since Im not a A380 pilot.
> > 
> > 
> > FWIW the IRL references I can find do not show the SPD above mach transition
> > image
> 
> What if your final cruising altitude is below an altitude where you would use Mach? This reference is using a cruise altitude of FL380. What if it's lower?
That issue of the dashed SPD value is unrelated to the PR when looking at the code. It is worth a new github issue however to be addressed in another PR.

**Comment by 2hwk** [comment]
Congratulations on your first merged contribution to the FBW project! You should have the contributor role in our discord and access to the contributors channel.

**Pull request merged**
