### PR TITLE
fix: undo change impacting performance in cpp logging

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes
A previous change in the logging library of the cpp framework caused a 10 fold increase in run time.
The expectation that the compiler optimizes away empty functions was not working out. 

Reverted to the previous version of logging code which also works well. 

Also added the {fmt] library and made logging.h use this instead (avoids issue with multiple lines in console when using << stream)

Discord username (if different from GitHub): cdr_maverick

## Testing instructions
Should not have any functional impact.

Framework is used by the FADEC, Pushback, Presets code. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by Saschl — APPROVED** [review]
LGTM, thanks for the quick fix!

**Review by tracernz — APPROVED** [review]
We should move fmtlib up to fbw-common/src when we can figure out how to convince cmake about it, but it's not a blocker. LGTM for me.

**Comment by tracernz** [comment]
Needs 0.13 changelog.

**Comment by Saschl** [comment]
Quality Assurance Tester Report

Discord Username : saschl
Object of testing : https://github.com/flybywiresim/aircraft/pull/9146
Aircraft : A380 and A320
Tier of Testing : 1
Date : 27/10/2024

Testing Process:

Spawned C&D. Did the setup and started the engines. Performed a pushback  without issues. Also runtime of the wasm modules is back to normal.

Negatives: N/A
Testing Results:
Passed

**Pull request merged**
