### PR TITLE
feat(fmgc): selected navaids reset on done phase

### LINKED ISSUE #8740: FMS: Manually tuned navaids not deleted in DONE phase
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-04T19:47:34+00:00",
    "ref": "refs/heads/master",
    "sha": "74e195a8ce4d0b1dbe7fe7dce046f7e6c4b44aff",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:74e195a8",
    "version": "a32nx-v0.12.0-dev.74e195a"
}
```

### Describe the bug

Manually tuned navaids during the flight are not detuned after landing.

### Expected behavior

FMS should delete the manually tuned navaids once it changes to DONE phase.

### Steps to reproduce

1) Perform a flight and manually tune a VOR for example through the RAD NAV page.
2) After landing, the "M" flag remains visible on the ND and the VOR remains tuned.

### References (optional)

https://youtu.be/Lqn0kKWhngM?t=499

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #8740

## Summary of Changes

- Rip a bandaid off and refactor the flight phase to use the event bus.
- Selected navaids reset on entering the done phase.

## References

See linked issue.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Perform a full flight. Ensure the FMS works normally. Tune manually some navaids in the FMS. Ensure just after landing (30 seconds) that the navaids are all reset back to auto-tuned navaids (M flags disappear on the ND etc. See the linked issue for a video).

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
Fun type check issues from things that should note be pulling in the FMGC.

**Review by BlueberryKing — APPROVED** [review]
Nice cleanup

**Comment by tracernz** [comment]
Depends on https://github.com/flybywiresim/aircraft/pull/8840 first.

**Comment by tylerclt** [comment]
Quality Assurance Trainee Report

Discord: Tylerb780#3594
Object of testing: #8836  
Tier of Testing: 2
Date: 26/08/2024

Testing Process: 
1. Loaded into KATL for a flight to KJAX
2. Powered Aircraft on 
3. Went through a standard FMS and aircraft preflight 
4. Pushed back
5. Departed KATL on the VRSTY3 with the NOKIE Transition 
6. Tuned the Vienna VOR (VNA/116,50) and the Dublin VOR (DBN/113.10) during the climb to cruise and verified NAV AID identification 
8. Switched VORs to the Taylor VOR (TAY/112.90) and the Craig VOR (CRG/ 114.50) and verified NAV AID Identification
9. Started descent with the ODEHA1 STAR with the DUCHY transition. 
10. Setup for the ILS08Y approach from CEDOT
11.  Verified that the manually selected NAV AIDs went away within 30 seconds 
12. Parked and shutdown aircraft

 
Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Works as Intended

Media:

**Comment by nebj00la** [comment]
Quality Assurance Trainee Report

Discord Username  : nebj00la
Object of testing : #8836
Aircraft          : A32NX
Tier of Testing   : 2
Date              : 26/08/2024

Testing Process: 

1. Configured flight from KBOS to KPVD.
2. Set up departure on PATSS7.
3. Tuned to Providence VOR during cruise and verified NAV AID ID.
4. Configured ILS runway 23 approach.
5. Verified approximately 30 seconds after landing (used CHRONO button) the NAV settings reset on the "RAD NAV" page of the FMS.

Testing Results: 
Passed

Media:

**Pull request merged**
