### PR TITLE
feat(a380x/mfd): Add ATCCOM connect page

### PR DESCRIPTION
**Pull request by heclak**
## Summary of Changes

- [x] Add ATCCOM connect page
- [x] Tweak ATCCOM header to fit header buttons with two lines of text
- [x] Changed the redirect url to drop "notification" as the isn't a separate notification page anymore
- [x] Update button for ADS-C section to match visual design and functionality

## Screenshots (if necessary)

image

## References

image

## Additional context

Discord username (if different from GitHub): Heclak

## Testing instructions

1. Switch to ATC COM page via the various methods
    1. Switch to ATC COM via  MFD system menu
    2. Switch at ATC COM by pressing ATCCOM key on the KCCU

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Comment by heclak** [comment]
Added new implementation of ADS-C button. I tried using the SurvButton class initially but there are some visual and function differences that would require a number of messy workarounds. 

image

Looking through the code, it seems that the full functionality of the ATCCOM might not be ready for implementation? I'm not sure if the ATSU is implemented enough to hook up to the CONNECT page. Should this be paused at the layout implementation only?

**Comment by BravoMike99** [comment]
> Added new implementation of ADS-C button. I tried using the SurvButton class initially but there are some visual and function differences that would require a number of messy workarounds.
> 
> image
> 
> Looking through the code, it seems that the full functionality of the ATCCOM might not be ready for implementation? I'm not sure if the ATSU is implemented enough to hook up to the CONNECT page. Should this be paused at the layout implementation only?

Don't think the ATSU/CPDLC backend is in the A380 at the moment as evidenced by sven in the discord (https://discord.com/channels/738864299392630914/1298664207482617886/1305068979626315776) so for now you have to  stick with only the layout is my understanding.

**Comment by heclak** [comment]
> 
> Don't think the ATSU/CPDLC backend is in the A380 at the moment as evidenced by sven in the discord (https://discord.com/channels/738864299392630914/1298664207482617886/1305068979626315776) so for now you have to stick with only the layout is my understanding.

Sounds good. I need to fix the additional "/" in the page title and I think I should be done with this page. Should I leave the placeholder text in there too?

**Comment by heclak** [comment]
Updated the page with the request to overlay a "Not Yet Implemented" label. (https://discord.com/channels/738864299392630914/981225551354282035/1306062447504920627)

image

**Comment by heclak** [comment]
> Ready for review, @heclak please pull changes locally as I've merged master into your branch

Thanks. Pulled and checked on my end. Code still working as expected on my end after merge.

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord Username: 2cas
Object of testing: #9491
Aircraft: A380X
Tier of Testing: 1
Date: 15/11/2024 

Testing Process: 
 
- [x] Switch to ATC COM page via the various methods
- [x] Switch to ATC COM via MFD system menu
- [x] Switch at ATC COM by pressing ATCCOM key on the KCCU

Testing Results: 
QA Passed 

Negatives:       

- N/A 

Conclusions: 

Good start, LGTM

**Comment by G-DRAW** [comment]
The only thing missing is the letter D on the ATIS tab.

**Comment by 2hwk** [comment]
Congratulations on your first merged contribution to FBW! You should now have the contributor role on discord and have access to the contributors channel.

**Comment by heclak** [comment]
> The only thing missing is the letter D on the ATIS tab.

Yea. I just noticed that as I was working on the D-ATIS page. I'll add that together in the D-ATIS PR.

**Comment by G-DRAW** [comment]
Hi heclak,
Well done on the ATC COM Page.

**Pull request merged**
