### PR TITLE
feat(fms): allow SID name to be displayed on the ND

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #[issue_no]

## Summary of Changes

Allows FMS to publish SID identifier to ND as found on A380 & A350 aircraft currently. 
## Screenshots (if necessary)

image

## References

A380/A350 FCOM, YT videos & preview picture of feature on A320

## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

A32NX: Perform a normal flight and verify approach identifier shows on the ND as before, in addition, no SID name should be displayed on the ND during preflight & takeoff/climb (like the attached picture). 
A380:
1) Insert a SID on the flightplan and verify the SID name appears on top of ND.
2) Fly the SID and perform a direct to a point of the SID prior to the final one, SID name should remain visible.
3) Verify SID name disappears after last waypoint of SID is sequenced, or, after performing a direct to the last SID waypoint.
4) Insert a SID and cruise flight level in a way that it will be reached before the end of SID. Verify that the SID name disappears once cruise level is reached.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
I feel like this is best implemented in the A380 ND + FMS only rather than a feature flag.

**Comment by Benjozork** [comment]
> I feel like this is best implemented in the A380 ND + FMS only rather than a feature flag.

The goal is to not have specific "380 FMS" sources as much as possible, so this has to go through a feature flag, like every other configurable aspect of the flight plan management that was added because it's different between 320/380 or different 320 FMS software versions.

Agree for the ND though.

**Comment by tracernz** [comment]
> The goal is to not have specific "380 FMS" sources as much as possible, so this has to go through a feature flag, like every other configurable aspect of the flight plan management that was added because it's different between 320/380 or different 320 FMS software versions.

The downside of that is a ton of unused bytecode for performance models, different implementations of things (e.g. holds), all being in memory for both planes, and a ton of messy code to cover differences in interfaces to other aircraft systems. It would be better to inject those from the plane.

**Comment by BravoMike99** [comment]
> > The goal is to not have specific "380 FMS" sources as much as possible, so this has to go through a feature flag, like every other configurable aspect of the flight plan management that was added because it's different between 320/380 or different 320 FMS software versions.
> 
> The downside of that is a ton of unused bytecode for performance models, different implementations of things (e.g. holds), all being in memory for both planes, and a ton of messy code to cover differences in interfaces to other aircraft systems. It would be better to inject those from the plane.

Is there a way to achieve this with the current code structure or will it have to wait? I don't mind adapting the code so that it is specific to the 380 FMS considering there is some base structure in place to achieve this.

**Review by tracernz — APPROVED** [review]

**Comment by pilotseyea350** [comment]
Quality Assurance Tester Report

Discord Username  : PilotEyesA350 
Object of testing : #8782  
Aircraft          : A380X 
Tier of Testing   : 2
Date              : 17/10/2024 

Testing Process: 
1. Load at EDDF
2. Choose MARUN2G SID
3. Verify SID appears on ND
4. Fly SID and insert a DIR TO to the penultimate WPT
5. SID on ND disappeared   

Testing Results: 
Not Passed  

Negatives:       
SID on ND disappeared after insering a DIR TO to the penultimate WPT

Conclusions: 
Not passed

Media:

**Comment by BravoMike99** [comment]
> Quality Assurance Tester Report
> 
> Discord Username : PilotEyesA350 Object of testing : #8782 Aircraft : A380X Tier of Testing : 2 Date : 17/10/2024
> 
> Testing Process:
> 
> 1. Load at EDDF
> 2. Choose MARUN2G SID
> 3. Verify SID appears on ND
> 4. Fly SID and insert a DIR TO to the penultimate WPT
> 5. SID on ND disappeared
> 
> Testing Results: Not Passed
> 
> Negatives: SID on ND disappeared after insering a DIR TO to the penultimate WPT
> 
> Conclusions: Not passed
> 
> Media:

Do you know which waypoint you performed the direct to and what the route/fms data was? I tested the MARU2G out of 07C earlier with a direct to LORPA and the SID name remained displayed. Reason why I ask is that if the FMS is not in the takeoff or climb phase, the SID name will disappear

**Comment by pilotseyea350** [comment]
> > Quality Assurance Tester Report
> > Discord Username : PilotEyesA350 Object of testing : #8782 Aircraft : A380X Tier of Testing : 2 Date : 17/10/2024
> > Testing Process:
> > 
> > 1. Load at EDDF
> > 2. Choose MARUN2G SID
> > 3. Verify SID appears on ND
> > 4. Fly SID and insert a DIR TO to the penultimate WPT
> > 5. SID on ND disappeared
> > 
> > Testing Results: Not Passed
> > Negatives: SID on ND disappeared after insering a DIR TO to the penultimate WPT
> > Conclusions: Not passed
> > Media:
> 
> Do you know which waypoint you performed the direct to and what the route/fms data was? I tested the MARU2G out of 07C earlier with a direct to LORPA and the SID name remained displayed. Reason why I ask is that if the FMS is not in the takeoff or climb phase, the SID name will disappear

I used a direct to LORPA but I will try again and let you know

**Comment by pilotseyea350** [comment]
Quality Assurance Tester Report

Discord Username : PilotEyesA350
Object of testing : #8782 
Aircraft : A380X
Tier of Testing : 2
Date : 19/10/2024

Testing Process:

1. Load at EDDF
2. Choose MARUN2G SID
3. Verify SID appears on ND
4. Fly SID and insert a DIR TO to LORPA
5. Verify SID appears on ND
6. Insert DIR TO MARUN
7. Verify SID disappears on ND
8. Reoad at EDDF
9. Choose MARUN2G SID
10. Verify SID appears on ND
11. Set CRZ FL at 050
12. Fly the SID and once reaching FL050, verify SID disappears from ND

Testing Results:
Passed

Negatives:

N/A

Conclusions:
Passed

Media:
N/A

**Pull request merged**
