### PR TITLE
feat(a380/mfd): status and switching page

### PR DESCRIPTION
**Pull request by Frenkii**
Fixes #[issue_no]

## Summary of Changes

Creation of the SURV -> STATUS & SWITCHING page.
TCAS 1 is reacting on the TCAS FAULT Simvar.

## Screenshots (if necessary)

grafik

## Additional context

Discord username (if different from GitHub):
frenkii

## Testing instructions

1.  Access the Status and Switching page via the SURV menu.
1. Buttons SYS 1 and 2 should have hover effect but no function.
1. Set Simvar TCAS fault to 1 -> TCAS 1 should switch to amber color.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by flogross89** [comment]
Very nice, thank you! Please notify us if it's ready for review

**Comment by Frenkii** [comment]
Basically it's nearly finished.

What do you think? Leave SYS 2 completely in mode "OFF", since it's not implemented?

**Comment by Frenkii** [comment]
I decided now to _hardcode_ SYS 2 as OFF.
In general, I am not sure, what's the best way to handle the different status of the systems, but the layout of the page is set up so far.

**Comment by flogross89** [comment]
> I decided now to _hardcode_ SYS 2 as OFF. In general, I am not sure, what's the best way to handle the different status of the systems, but the layout of the page is set up so far.

That's reasonable, we can connect the other systems when they are implemented

**Comment by BravoMike99** [comment]
Hi, thanks for the contribution. On the FWS side it currently uses the same variable for TCAS 1 & TCAS 2 fault  as there's no two systems as floridude mentioned but I guess its fine to leave your implementation as is (only tcas 1). Also, please add an entry to the changelog.md file :)

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Needs Testing Instructions

**Comment by 2hwk** [comment]
Quality Assurance Tester Report

Discord Username: 2cas
Object of testing: #9362
Aircraft:  A380X
Tier of Testing: 1
Date: 16/11/2024 

Testing Process: 
- [x] Access the Status and Switching page via the SURV menu.
- [x] Buttons SYS 1 and 2 should have hover effect but no function.
- [x] Set Simvar TCAS fault to 1 -> TCAS 1 should switch to amber color.
- [x] Turned off ADR1 to fault the TCAS computer -> TCAS1 turned amber


Testing Results: 
QA Passed

Negatives:       
- N/A

Conclusions: 
- LGTM

**Pull request merged**
