### PR TITLE
feat(flight_model): Add drag from landing lights

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #[issue_no]

## Summary of Changes

We already have gear door drag that is added through changing MSFS gear position behind the scene.

Now we also add landing light position to add more drag when they are extended as well as RAT.

## References

FCOM states up to 1% more fuel consumption when lights are extended

## Additional context

Discord username (if different from GitHub):

## Testing instructions

This can impact gear mechanisms and ground collision, so quite some non regression tests to do when landing, and also trying to land with no gear / only left gear (using gear actuator failure) / only nose etc....

1) Check drag from landing lights: 
-Steady speed autothrust on. 
-Extend landing lights. 
-Check increased engine power from auto thrust

2) Check drag from RAT: 
-Steady speed autothrust on. 
-Extend RAT. 
-Check increased engine power from auto thrust

3) Check gear door drag still works : 
-Steady speed autothrust on.
-2 turns on gravity gear handle
-Check increased engine power from auto thrust

4) Check gear drag:
-Steady speed autothrust on.
-3rd turn of gravity gear handle
-Check increased engine power from autothrust

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by alepouna** [comment]
QA Report

Discord: alepouna
Object of testing: #8554  
Tier of Testing: 1
Date : 6/3/2024

Testing Process:
1. Check drag from landing lights:
- Steady speed autothrust on.
- Extend landing lights.
- [PASS] Check if any impact on engine parameters

2. Check door drag still works :
- Steady speed autothrust on.
- 2 turns on gravity gear handle
- [PASS] Check increased engine power from auto thrust

3. Check gear drag:
- Steady speed autothrust on.
- 3rd turn of gravity gear handle
- [PASS] Check increased engine power from autothrust

Performed a rough and soft landing as well, no issues. 

Testing Results:
Passed

**Comment by donstim** [comment]
One request here. Can you change the cruise.flt file so that the landing lights are fully retracted and the nose light is off if a flight is started in the cruise condition? Just need to set the LVARs appropriately. Thanks.

**Comment by dragold** [comment]
QA Tester Report 

Name: Mr.Blank#7677
Date of testing MM/DD/YYYY:03/11/2024-03/12/2024
PR Tested: 8554
Tier of testing:?

Testing technique: tryouts
Test Instructions:
Check drag from landing lights:
Steady speed autothrust on:
-Extend landing lights.
-Check increased engine power from auto thrust
Check drag from RAT:
-Steady speed autothrust on.Extend RAT.
-Check increased engine power from auto thrust
Check gear door drag still works :
-Steady speed autothrust on.
-turns on gravity gear handle
-Check increased engine power from auto thrust
Check gear drag:
-Steady speed auto thrust on.
-3rd turn of gravity gear handle
-Check increased engine power from auto thrust
Additional :
change the cruise.flt file so that the landing lights are fully retracted and the nose light is off if a flight is started in the cruise condition
Methodology
All as per instruction + Additional  
Condition clear weather with/without CFD 
debug aircraft drag Check
Negatives: NIL

Testing Results: PASS

**Comment by donstim** [comment]
Some quantitative data here. First screenshot shows landing lights and RAT retracted at FL 310, M0.78, ISA, no wind, 60 T, steady-state cruise condition (Thrust=Drag):
Lights and RAT retracted, FL310, M0 78 60T

Total fuel flow is 1094+1081 = 2175 kg/hr

Now, with 1 landing light extended:
1 Landing Light extended, FL310, M0 78 60T

Added drag coefficient is 0.00023. Total fuel flow is 1101+1088 = 2189 kg/hr (increase of 0.6%)

Next, with 2 lights extended:
Two Landing Lights extended, FL310, M0_78, 60T

Added drag coefficient is 0.00046. Total fuel flow is 1109+1096 = 2201 kg/hr (increase of 0.6% per landing light)

Finally, with the RAT extended
RAT extended, FL310, M0_78, 60T

Added drag coefficient is 0.0084. Total fuel flow is 1120+1107 = 2227 (increase of 2.4%)

I also verified that these additional drag values were applied when the lights and RAT were extended at speeds above (280 KCAS) and below (240 KCAS) the speeds at which the landing gear extension would be locked out. I also confirmed that when the gear is retracted with the lights and/or RAT extended, the lights and RAT drag remained.

**Comment by donstim** [comment]
> One request here. Can you change the cruise.flt file so that the landing lights are fully retracted and the nose light is off if a flight is started in the cruise condition? Just need to set the LVARs appropriately. Thanks.

Done

**Pull request merged**
