### PR TITLE
feat: selected heading track line + other nd fixes (for afpm)

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #[issue_no]

## Summary of Changes

Adding track line and dashed flight plan in HDG

## References

Dashed flight plan (green dashed line) - ARC/ROSE NAV mode
Conditions:
- LNAV is not armed or engaged
- LNAV is armed but does not intercept currently active leg

Plan mode:
- LNAV is not armed - (and no secondary fpln)

## Additional context

Discord username (if different from GitHub):2Cas#1022

## Testing instructions

- Test with no flight plan, AP On/Off. Track line should show in selected mode with AP on, Flight plan should be dashed if hdg knob is pulled. 
- Check that temporary flight plan is unaffected (Enter SID/STAR and do not insert, see ND)
- Also check in every spawn state (on runway, C&d, in midair)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Gabriellscorreia0001** [comment]
Quality Assurance Tester Report
Discord:  Gabriellscorreia#0001
Object of testing: #5982
Tier of Testing: 1
Date: 10/10/2021 {Z-2}

Testing Process:
* Spawned in SBJU

* Tested first without any plan, the track line works perfectly as shown in photo 1, AP ON/OFF does not affect the functioning.

* Second test in SBJU also, Runway 31 with flight plan, as seen in photo 2 the flight plan was dashed.

* The temporary flight plan was not affected by the track line.

* Flight status does not change line operation

Negatives: - Nothing

Testing Results: Passed
Conclusions: Works fine, great work guys

Image 1
Test 1
t.com/88603173/136682492-ba39415a-1d3d-497b-b316-08b1b4874aa5.PNG)

Image 3
Test 3

Great work

**Comment by 2hwk** [comment]
> Not sure if this was introduced by this PR, Spawned on the RW EGJJ ready to test. No flight plan entered. Selected different modes for ND. If PLAN is selected the ND is black and cannot be recovered by selecting another mode. Repeatable.
> 
> Edit. Checking. The pics above do not have INOP below TERR ON ND. When I download and use this PR I do. The PR indicates it is to be merged with cFPM branch. Should there be INOP stickers? If not ignore the above ND .

There was an issue introduced by the last change, it's been fixed, try again.

**Comment by 2hwk** [comment]
> > > Not sure if this was introduced by this PR, Spawned on the RW EGJJ ready to test. No flight plan entered. Selected different modes for ND. If PLAN is selected the ND is black and cannot be recovered by selecting another mode. Repeatable.
> > > Edit. Checking. The pics above do not have INOP below TERR ON ND. When I download and use this PR I do. The PR indicates it is to be merged with cFPM branch. Should there be INOP stickers? If not ignore the above
> > 
> > 
> > There was an issue introduced by the last change, it's been fixed, try again.
> 
> I downloaded the artefact about 0900z this morning. Is it a very recent fix? In any case I will re download and try again this evening.

Yes there's another fix, redownload the latest build and try again, it should resolve the issue.

**Comment by marcman86** [comment]
> When loading in on the runway with no flight plan there is always a solid line pointing somewhere random even though you load in while on heading mode

Hi, this reminds me on #5804

**Pull request merged**
