### PR TITLE
feat(a380x): air conditioning and ventilation ecam messages

### PR DESCRIPTION
**Pull request by mjuhe**
## Summary of Changes

Adds 43 new ECAM warnings based on the ATA 21 failures introduced in #8883 . This is part 1 and includes only air cond and ventilation warnings - pressurization will be added on a separate PR.

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub): Commander Ga

## Testing instructions

By EFB failure (N/A warnings will be implemented in the future):
- Rapid Decompression: N/A
- Cabin Fans (1-4): ECAM warning "ONE, TWO, THREE, ALL PRIMARY CABIN FANS FAULT" (depending on how many you fail). The COND page shows fans in orange.
- Hot Air Valve: Nothing happens when failed if it doesn't disagree with commanded position. Try failing the valve and pressing the overhead button (to force it to close). An ECAM warning appears "HOT AIR XX VLV OPEN" and the valve turns amber on the COND page. Or do the opposite (close it first, fail it, then press the button again) and get a "HOT AIR XX FAULT" warning. Note the hot air valve is slow to react so these warnings take a few seconds to appear.
- Fwd/Bulk Cargo Isolation Valve: The valve closes, the ventilation fan stops and you get an ECAM warning "FWD/BULK CARGO VENT FAULT". The overhead button gets a FAULT amber light.
- Fwd/Bulk Cargo Extraction Fan: No ECAM warning. The fan appears in amber in the COND page.
- Bulk Cargo Heater: ECAM warning "BULK CARGO HEATER FAULT". An amber HEATER warning apprears in the COND page. The amber FAULT light illuminates in the overhead button.
- FDAC XX Channel XX: When failing one channel, an ECAM warning "PACK XX CTL XX FAULT" appears. When failing two channels of the same FDAC, a "PACK XX FAULT" warning appears and the overhead FAULT light illuminates.
- TADD Channel XX: When failing one channel, an ECAM warning "TEMP CTL XX FAULT" appears. When both, "TEMP CTL FAULT" appears.
- Fwd/Aft VCM Channel XX: When failing one channel, an ECAM warning "FWD/AFT VENT CTL XX FAULT" appears. When failing two channels of the same VCM, a "FWD/AFT VENT CTL FAULT" warning appears. (note IEFC pb not implemented yet)
- OCSM(...): N/A
- AGS Applications: B1 and B3 control pack 1, B2 and B4 control pack 2. Failing one will trigger a "PACK XX CTL REDUNDANCY LOST". Failing two of the same pack will show a "PACK XX CTL DEGRADED"
- TCS Applications: Any number of failures will trigger "TEMP CTL REDUNDANCY LOST". All failures will trigger "TEMP CTL DEGRADED".
- VCS Applications: B1 and B3 control fwd vent, B2 and B4 control aft vent. Failing one will trigger a "FWD/AFT VENT CTL REDUNDANCY LOST". Failing two of the same vent will show a "FWD/AFT VENT CTL DEGRADED".
- CPCS Applications: N/A

Other ECAM warnings:
- In flight with packs off will give you a "PACK XX OFF" warning (60 seconds delay after take off)
- In flight with hot air off will give you a "HOT AIR XX OFF" warning
- In flight with both packs off or failed will give you a "PACK 1+2 FAULT" (180 seconds delay after take off)

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]

**Comment by mjuhe** [comment]
Sorry @2hwk ! Deleted too many lines when I was cleaning up unused code. Fixed now and tested on my end.

**Comment by Popespice** [comment]
Quality Assurance Tester Report

Discord Username  : popepsice
Object of testing : #9060 
Aircraft          : A380X
Tier of Testing   : 2
Date              : 118102024

Testing Process: 
Followed testing procedure outlined in PR

Testing Results: 
Not Passed

Negatives:       
ENG DU messages did not all populate ( specifically 1. In flight with hot air off will give you a "HOT AIR XX OFF" warning
2. In flight with both packs off or failed will give you a "PACK 1+2 FAULT" (180 seconds delay after take off))
3. Overhead lights for cargo isolation valves did not display FAULT on them
Conclusions: 
Not Passed

**Comment by mjuhe** [comment]
Thanks for the test @Popespice ! Would you be able to describe what steps you followed? I just tried my build and I can get the three warnings you say didn't appear (please keep in mind the "PACK 1+2 FAULT" will take 3 minutes after take off to show). Feel free to ping me on Discord 😉.

image

**Comment by Popespice** [comment]
Quality Assurance Tester Report

Discord Username  : popespice
Object of testing : #9060 
Aircraft          : A380X
Tier of Testing   : 2
Date              : 20102024

Testing Process: 
1. Load into the sim
2. Power on airplane as normal
3. Go into EFB and test every aspect of failure mode ATA-21
4. Observe all failure points work and throw ECAM messages

Testing Results: 
Passed

Negatives:       
N/A

Conclusions: 
Working as intended

**Pull request merged**
