### PR TITLE
fix: show preselected speed and mach accordingly

### LINKED ISSUE #8217: PFD SPEED SEL message
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-16T06:20:39+00:00",
    "ref": "refs/heads/master",
    "sha": "4783ebcadace8462bc71af4f8c1bb4c1ebdb322c",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:4783ebca",
    "version": "v0.11.0-dev.4783ebc"
}
```

### Describe the bug

The SPEED SEL message in the line 3 of the FMA it's missing the ":".
It displays "SPEED SEL 225"

### Expected behavior

Should display "SPEED SEL: 225"

### Steps to reproduce

1. Prior to takeoff, presel a speed in PERF CLB
2. During climb check the 3rd line of the FMA

### References (optional)

DSC-22_30-80-20
image

https://youtu.be/RhyQK7Jz56g?t=94

### Additional info (optional)

This was tested with a preselected CLB speed, but should be the same for preselected CRZ speed

### Discord Username (optional)

Bernardo R

### PR DESCRIPTION
**Pull request by aaronschweig**
Fixes #8217

## Summary of Changes

I added the colons to the `SPEED SEL` and `MACH SEL` messages in the `FMA.tsx`

## References

Shown in the original issue #8217 

## Additional context

This is my first PR in this Repo - if I missed something or did something wrong please let me know - happy to learn!

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by BlueberryKing** [comment]
Hi, thank you for the PR! Can you add a changelog entry? Also, I'm a bit unsure if there is a space after the colon, but I'd have to compare how it looks in the sim vs. the references.

**Review by tracernz — APPROVED** [review]

**Comment by tracernz** [comment]
Should have a changelog entry.

**Comment by aaronschweig** [comment]
Hey sorry for the long delay, real life came in!

I took some screenshots from in the sim:

SPEED SEL:
<p align=center>
SPEED SEL
</p>

MACHSEL:
<p align=center>
MACH SEL
</p>

After comparing it with the example in the original issue it looks like the space should go away, but I could also be mistaken due to the angle of the screenshot in the original issue. But also wrt to the reference manual provided by @becas22 it looks like there should not be a space. What do you think?

**Comment by becas22** [comment]
@aaronschweig yeah, looks like the space needs to go. Can you provide some screenshots without the space?

**Comment by tshomas** [comment]
Got this one today from work

PXL_20230927_064133817

**Comment by aaronschweig** [comment]
Here is a screenshot without the space:

image

**Comment by becas22** [comment]
From Shomas pic it seems that:

- the ":" are aligned at the bottom of the line;
- There seems to be some space but not a whole one.

@aaronschweig do you think these are possible to implement? Otherwise I would say that the one without the space looks the best

**Comment by aaronschweig** [comment]
I played around a bit, but making it smaller or try fiddleing with the whitespace would involve messing with the `text` node of the svg in one way or the other. I couldn't figure out a way that looks right and works with a reasonable amount of changes in the code.

Also one question to the changelos: Is it just written by myself or autogenerated?

**Comment by becas22** [comment]
Then I would say that it looks better now (without the space) that what it was before (with no : at all)

I would say that the changelog needs to be done by you. Take a look at this PR by BBKing for example: https://github.com/flybywiresim/aircraft/pull/8205/commits/be80aa9a02e7f639d4274d930cff412d02b8d665

**Comment by tshomas** [comment]
PXL_20230930_192526282

Another one, not the clearest unfortunately though!

**Comment by BravoMike99** [comment]
Hi @aaronschweig  do you plan on working this further? I wouldn't mind taking a look at this issue in case you don't plan to.

**Comment by aaronschweig** [comment]
Hey @BravoMike99 yes please feel free to continue and make changes!

**Comment by Maximilian-Reuter** [comment]
Closed as continuation is happening in different PR

**Pull request closed without merging**
