### PR TITLE
fix: Tweaks to takeoff performance calculator to improve accuracy

### PR DESCRIPTION
**Pull request by donstim**
Fixes #[issue_no]

## Summary of Changes
Tweaks to some of the coefficients used to calculate takeoff weight capability, Flex temperatures, and speeds to improve accuracy.
## Additional context

Discord username (if different from GitHub): donbikes

## Testing instructions
Try different runways, takeoff configurations, and bleed settings and make sure it still gives sensible results.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by donstim** [comment]
This turned out to be more than just a few tweaks here and there. Found a number of typos that had been missed previously as well.  There are also a few items for @tracernz to fix in the code.

**Comment by pilotseyea350** [comment]
Quality Assurance Trainee Report

Discord          : piloteyesa350
Object of testing: 8804
Tier of Testing  : 1
Date             : 21/08/2024

Testing Process: 
- Power up at EDDM
- Start EFB
- Perform Calculations with different weights, Flap config, bleed config, anti-ice config, different Runway
- Test performed for: EDDM, EDDF, LOWI, LEPA
- Comparison with Shomas' Perf CALC
- Variation between TOGA and FLEX v-speeds are 8% (compared to 7% with Shomas' calculations)

Negatives:       
V-Speeds are slower than an IRL NEO performance calc for the same config. 

Testing Results: 
Passed

Conclusions: 
Probably need a more extensive test with certified pilots to improve accuracy in the future.

**Comment by donstim** [comment]
> Quality Assurance Trainee Report
> 
> Discord : piloteyesa350 Object of testing: 8804 Tier of Testing : 1 Date : 21/08/2024
> 
> Testing Process:
> 
> * Power up at EDDM
> * Start EFB
> * Perform Calculations with different weights, Flap config, bleed config, anti-ice config, different Runway
> * Test performed for: EDDM, EDDF, LOWI, LEPA
> * Comparison with Shomas' Perf CALC
> * Variation between TOGA and FLEX v-speeds are 8% (compared to 7% with Shomas' calculations)
> 
> Negatives: V-Speeds are slower than an IRL NEO performance calc for the same config.
> 
> Testing Results: Passed
> 
> Conclusions: Probably need a more extensive test with certified pilots to improve accuracy in the future.

Thank you for the test. Can your provide screenshots (or details in some other way) of the comparisons (particularly of the IRL calcs)?

**Comment by pilotseyea350** [comment]
> > Quality Assurance Trainee Report
> > Discord : piloteyesa350 Object of testing: 8804 Tier of Testing : 1 Date : 21/08/2024
> > Testing Process:
> > 
> > * Power up at EDDM
> > * Start EFB
> > * Perform Calculations with different weights, Flap config, bleed config, anti-ice config, different Runway
> > * Test performed for: EDDM, EDDF, LOWI, LEPA
> > * Comparison with Shomas' Perf CALC
> > * Variation between TOGA and FLEX v-speeds are 8% (compared to 7% with Shomas' calculations)
> > 
> > Negatives: V-Speeds are slower than an IRL NEO performance calc for the same config.
> > Testing Results: Passed
> > Conclusions: Probably need a more extensive test with certified pilots to improve accuracy in the future.
> 
> Thank you for the test. Can your provide screenshots (or details in some other way) of the comparisons (particularly of the IRL calcs)?

No worries ! Sure, I can provide the screenshots, We've also had discussions on the qa channel in discord with the team about that !
perf2
perf1
shom1
shom2

**Comment by Aleloplt** [comment]
Quality Assurance Trainee Report

Discord : Alelo
Object of testing: 8804
Tier of Testing : 1
Date : 21/08/2024

Testing Process: LFPG/EGPE/LOWI
Performed calcs with difference settings and temperatures. Didnt really test AI because not really been flying with it much atm.
Comparison with my flysmart for a NEO

LFPG
LFPG PACKS ON FLEX
WhatsApp Image 2024-08-21 at 16 55 38_e03d86f9
LFPG PACKS OFF FLEX
WhatsApp Image 2024-08-21 at 16 57 01_c0538d68
LFPG PACKS OFF TOGA
WhatsApp Image 2024-08-21 at 16 58 00_a1642359
LFPG PACKS ON TOGA
WhatsApp Image 2024-08-21 at 16 58 51_77ad93e1

EGPE
EGPE PACKS OFF FLEX
WhatsApp Image 2024-08-21 at 17 04 20_9ec105ad
EGPE PACKS OFF FLAP2
WhatsApp Image 2024-08-21 at 17 24 42_553abf98
WhatsApp Image 2024-08-21 at 17 08 08_43a557fb

LOWI
LOWI PACKS OFF FLEX
WhatsApp Image 2024-08-21 at 17 12 48_9431cb18
LOWI PACKS OFF FLEX HOTHIGH
WhatsApp Image 2024-08-21 at 17 14 48_1d2a2c86
LOWI PACKS OFF FLEX HOTHIGH OPTCONF
WhatsApp Image 2024-08-21 at 17 15 31_c893df77
LOWI PACKS OFF TOGA HOTHIGH
WhatsApp Image 2024-08-21 at 17 17 32_30db07ce

Testing Results:
Passed

Conclusions:
In some areas they varied differently such as at the longer runway airport. V speeds were 8 knots higher than Flysmart. But to be honest all seem really close.

**Comment by donstim** [comment]
Thank you for the detailed review!  Additional FlySmart data is always helpful.
For the LFPG comparisons, the A/C packs on calculation (and the A/I bleed calculations, too, for that matter) for the A32NX just uses a simple set of increments/decrements from the FCOM. These will be conservative compared to the first principles calculation done by FlySmart. The packs off comparison shows that the intended accuracy level of ~2 deg Flex and 2-3 knots in V2 speed were met. Flex may be closer after @tracernz completes some coding changes I requested.

For EGPE, note that you did not change the MSFS-reported TORA and the runway entry angle in the A32NX calc to match those used in the FlySmart calc.  If you had, the first one (CONF 1+F) would have been 2 degrees closer in Flex temp (meeting the target):
Screenshot 2024-08-21 133743

For the CONF 2 case, the same 2 degree change in the Flex temp would occur, but it would  be a bigger miss than I'd like to see (4 degrees). There is also a specific coding issue for CONF 2 short runway calcs that is being fixed here, but it would likely only get it another degree closer.

Again for the OPT case, correcting the inputs gets Flex temp closer, but still not as accurate as I would like: 
Screenshot 2024-08-21 135256
(For these short runways, being just a little off in MTOW vs temp can result in larger Flex temp errors!)

LOWI also has a 180 deg runway entry. The ability to input the runway entry angle is an exclusive for the A32NX that I included specifically for runways like this. :-) Here is the first result with the corrected input:
Screenshot 2024-08-21 140247

The second one didn't change with the corrected input. For the OPT comparison, the A32NX calculator has the Flex temps within 1 deg of each other for CONF 2 and 3. So a small error in either could alter the OPT configuration selection. I don't know if the known coding issue for CONF 2 will affect that case.

For the last comparison, you compared a CONF 1+F FlySmart cal to an OPT A32nx calc. Here is the CONF 1+F A32NX calc. It matches the FlySmart speeds much better:
Screenshot 2024-08-21 141458

**Comment by donstim** [comment]
While these tests were welcome, they weren't actually in conditions where the tweaks were made by this PR. In other words, the same results would have been obtained with the current dev version of the airplane and takeoff performance calculator. I guess they at least showed that this PR did not make these comparisons any worse.

**Pull request merged**
