### PR TITLE
feat(hyd): Placeholder logic to inhibit electrical backups

### LINKED ISSUE #9408: [A380X] EBHA Electrical Backup for flight control surfaces is active on ground and not inhibited
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

Mechanical backup mode is active on ground, should be inhibited (i.e. the control surfaces on the wings should not move without hydraulic power on ground).

### Expected behavior

None of the ailerons on the wings should not move without hydraulic power on ground.
Electrical backup (EBHA) offline, but shown as on standby and shown as green in the SD F/CTL page. 

All flight surfaces still have electrical back up on loss of hydraulics except the outer aileron.

### Steps to reproduce

1. Before Engine Start/ Hydraulics are active
2. Observe that the inboard ailerons still move with electrical backup mode on ground

### References (optional)

https://youtu.be/1QJSyeUBlU8?si=-bpunfd_kQnwz395

### Additional info (optional)

Reporting on behalf of a user on discord.

### Discord Username (optional)

m7amed7982

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #9408

## Summary of Changes

This is a placeholder logic in hydraulics so that electrical backups are only allowed when engine masters are on or in flight.
This is to be removed once this logic is correctly implemented in flight computers side.

Known issue: This does not provide feedback to ECAM flight control screen, so electrical backups still appear active.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- [ ] Control surfaces do not move on ground with no hydraulic pressure until first engine master is on.
- [ ] All EHA backups work properly in flight is hydraulics are lost totally, even if all engines master off in flight
- [ ] EHA backups still work properly in case of emergency landing with all engines master off (should deactivate after 2 minutes)

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Review by Gurgel100 — APPROVED** [review]

**Comment by CaptCrystal** [comment]
@2hwk Was the "QA A380 Only" label intended for this PR or no? I took a look at the code and it appears that there were no files changed for the A32NX

**Comment by Gurgel100** [comment]
> @2hwk Was the "QA A380 Only" label intended for this PR or no? I took a look at the code and it appears that there were no files changed for the A32NX

Yes this is intended because this only affects the A380X.

**Comment by CaptCrystal** [comment]
> > @2hwk Was the "QA A380 Only" label intended for this PR or no? I took a look at the code and it appears that there were no files changed for the A32NX
> 
> Yes this is intended because this only affects the A380X.

Yes, I should've clarified. Was the QA A380 Only label meant to remain on this PR? I thought it should've but I just wanted to make sure.

**Comment by 2hwk** [comment]
`QA A380 Only` Label is being retired since the A380X is now public and available to be tested for all testers.

**Comment by 2hwk** [comment]
Quality Assurance Tester Report

Discord Username: 2cas
Object of testing: #9466
Aircraft: A380X
Tier of Testing: 1
Date: 13/11/2024 

Testing Process: 
- [x] Control surfaces do not move on ground with no hydraulic pressure until first engine master is on.
- [x] All EHA backups work properly in flight is hydraulics are lost totally, even if all engines master off in flight
- [x] EHA backups still work properly in case of emergency landing with all engines master off (should deactivate after 2 minutes)

Testing Results: 
- QA Passed

Negatives:
- Start-up sequence still does not correctly match the video below, but as noted in the PR we need the flight computer implementation (flight computers themselves are also TODO) for this to be fully correct. Once that is done however this should now be fixed.

https://youtu.be/1QJSyeUBlU8?si=-bpunfd_kQnwz395

Conclusions: 

LGTM

**Pull request merged**
