### PR TITLE
feat(a380x/fms): nav db swap to reset fms

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

This implements equivalent nav db swap function to the A32NX, for quickly resetting the FMS state. It also fixes the database effectivity dates and db p/n.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by flogross89** [comment]
Thank you for the PR! We still have some data which is outside of flightPlanService (since we don’t have a/c specific performance data yet, and possibly need other modifications), so a bunch of data is stored in https://github.com/flybywiresim/aircraft/blob/master/fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.tsx#L52

We should also reset this data somehow, otherwise e.g the PERF/APPR page would remain filled

**Review by flogross89 — CHANGES_REQUESTED** [review]
See previous comment

**Comment by tracernz** [comment]
> Thank you for the PR! We still have some data which is outside of flightPlanService (since we don’t have a/c specific performance data yet, and possibly need other modifications), so a bunch of data is stored in https://github.com/flybywiresim/aircraft/blob/master/fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.tsx#L52
> 
> We should also reset this data somehow, otherwise e.g the PERF/APPR page would remain filled

Ah, that is reset by the initVariables function in the A32NX. Probably makes sense for the A380 to be the same.

**Comment by flogross89** [comment]
> > Thank you for the PR! We still have some data which is outside of flightPlanService (since we don’t have a/c specific performance data yet, and possibly need other modifications), so a bunch of data is stored in https://github.com/flybywiresim/aircraft/blob/master/fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.tsx#L52
> > We should also reset this data somehow, otherwise e.g the PERF/APPR page would remain filled
> 
> Ah, that is reset by the initVariables function in the A32NX. Probably makes sense for the A380 to be the same.

Yep. FmgcData could just get a reset() function and that’s it, all performance/FP data not in flightPlanService has to be stored in FmgcData. Parts of the SWAP nav db code could maybe also be called when transitioning to the FMGC DONE phase? Since we’re also trying to reset the FMC there

**Comment by tracernz** [comment]
> > > Thank you for the PR! We still have some data which is outside of flightPlanService (since we don’t have a/c specific performance data yet, and possibly need other modifications), so a bunch of data is stored in https://github.com/flybywiresim/aircraft/blob/master/fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.tsx#L52
> > > We should also reset this data somehow, otherwise e.g the PERF/APPR page would remain filled
> > 
> > 
> > Ah, that is reset by the initVariables function in the A32NX. Probably makes sense for the A380 to be the same.
> 
> Yep. FmgcData could just get a reset() function and that’s it, all performance/FP data not in flightPlanService has to be stored in FmgcData. Parts of the SWAP nav db code could maybe also be called when transitioning to the FMGC DONE phase? Since we’re also trying to reset the FMC there

It would be nice if the "unset" value for every field in the performance data was `null`. Then we could have a reset method that just loops through and sets everything to null, rather than an error prone reset method that you have to remember to add any new props to.

**Comment by flogross89** [comment]
> > > > Thank you for the PR! We still have some data which is outside of flightPlanService (since we don’t have a/c specific performance data yet, and possibly need other modifications), so a bunch of data is stored in https://github.com/flybywiresim/aircraft/blob/master/fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.tsx#L52
> > > > We should also reset this data somehow, otherwise e.g the PERF/APPR page would remain filled
> > > 
> > > 
> > > Ah, that is reset by the initVariables function in the A32NX. Probably makes sense for the A380 to be the same.
> > 
> > 
> > Yep. FmgcData could just get a reset() function and that’s it, all performance/FP data not in flightPlanService has to be stored in FmgcData. Parts of the SWAP nav db code could maybe also be called when transitioning to the FMGC DONE phase? Since we’re also trying to reset the FMC there
> 
> It would be nice if the "unset" value for every field in the performance data was `null`. Then we could have a reset method that just loops through and sets everything to null, rather than an error prone reset method that you have to remember to add any new props to. I think fixing this is well outside the scope of this PR, and also exists for the DONE phase, no? Also, that file is .tsx but contains no JSX..

Overlooked this comment, sorry. Yeah we can also fix this outside of this PR, fine for me.

**Review by flogross89 — APPROVED** [review]

**Comment by tracernz** [comment]
> Overlooked this comment, sorry. Yeah we can also fix this outside of this PR, fine for me.

To track it: https://github.com/flybywiresim/aircraft/issues/9019

**Pull request merged**
