### PR TITLE
fix: Fixed input parser for ICAO for weather widget

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes
The flyPad Weather Widget started requesting METAR information for invalid ICAOs which when for example entering "EDD," led the api to return ALL available metar and the flyPad to try to display these. This also caused the sim to freeze in some cases.

This PR improves the input validation to avoid this in the future. 

## Screenshots (if necessary)
image

Discord username (if different from GitHub): cdr_maverick

## Testing instructions
Try to enter valid and invalid ICAOs and make sure the Weather Widget behaves correctly. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
The length check is redundant; it’s all contained in the regex.

**Comment by frankkopp** [comment]
> The length check is redundant; it’s all contained in the regex.

I know but it might already avoid to run the expensive regex in most cases (while typing)

**Comment by Maximilian-Reuter** [comment]
> > The length check is redundant; it’s all contained in the regex.
> 
> I know but it might already avoid to run the expensive regex in most cases (while typing)

did you notice any input delay or impact on frametimes ?

**Comment by frankkopp** [comment]
> > > The length check is redundant; it’s all contained in the regex.
> > 
> > 
> > I know but it might already avoid to run the expensive regex in most cases (while typing)
> 
> did you notice any input delay or impact on frametimes ?

No but with regex this is just good practice to avoid them to run at all. And a simple length check is always better than to run a regex.

**Review by 2hwk — APPROVED** [review]

**Comment by noonebling** [comment]
Quality Assurance Trainee Report

Discord          : noonebling
Object of testing: 8587
Tier of Testing  : 1
Date             : 27/03/2024

Testing Process: 
Try to enter valid and invalid ICAOs and make sure the Weather Widget behaves correctly.

Negatives:
N/A

Testing Results: 
Passed

Conclusions: 
Works as expected

**Pull request merged**
