### PR TITLE
fix(a380x): prevented clickspots being activated behind L/G GVTY master guard

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #[issue_no]

## Summary of Changes

Fixes an issue with clickspots on the L/G GVTY lever.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Check the L/G GVTY extension switch can NOT be moved through the L/G GVTY guard
- Check that L/G GVTY extension switch can be moved once the guard is lifted
- Check that manual L/G GVTY extension guards (two red) still operate as per normal.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
Can't we just use a collision mesh on the lid to keep it simple?

**Comment by becas22** [comment]
Quality Assurance Report

Discord Username  : bernardor96
Object of testing : #8973  
Aircraft          : A380X 
Date              : 24/09/2024 

Testing Process: 
Check the L/G GVTY extension switch can NOT be moved through the L/G GVTY guard
Check that L/G GVTY extension switch can be moved once the guard is lifted
Check that manual L/G GVTY extension guards (two red) still operate as per normal. 


Testing Results: 
Passed  


Negatives:       
Clickspots visible without interaction, as visible in media below.
Red guards clickspots could be changed to hand cursor instead of arrows

Conclusions: 
The PR achieves its scope. Not displaying the clickspots with the guard down would be better imo

Media:
https://discord.com/channels/738864299392630914/1193615390861951086/1288094710807658506

**Comment by 2hwk** [comment]
> Can't we just use a collision mesh on the lid to keep it simple?

We could, but then this would still work either way as a backup if that doesn't work. Also this seems to work nicer with the non-legacy interaction system.

**Review by alepouna — APPROVED** [review]
xml wise lgtm

**Pull request merged**
