### PR TITLE
fix(fms): use station declination for pbx/pbd

### LINKED ISSUE #9095: fms: station declination not used for pbd/pbx
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Fixed in https://github.com/flybywiresim/aircraft/pull/8182 and then regressed in https://github.com/flybywiresim/aircraft/pull/7692

### Expected behavior

Should use station declination for VOR type facilities.

### Steps to reproduce

Enter a PBD or PBX from a station(s) where the station declination is markedly different from the current WMM magnetic declination.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by BlueberryKing**
Fixes #9095 

## Summary of Changes

Uses station declination as magvar instead of database for PBX/PBD waypoints. This has been fixed before but regressed in fms-v2.

## Screenshots (if necessary)

Before (KSFO Quiet Bridge Visual)
Screenshot 2024-10-20 124239

After
Screenshot 2024-10-20 125049

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Use testing instructions of original PR https://github.com/flybywiresim/aircraft/pull/8182

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Review by tracernz — APPROVED** [review]

**Comment by IntegrierterKurde** [comment]
Non QA Member Report (Alepouna has authorized submitting this report)

Discord Username  : aliexpress4291 
Object of testing : #9103 
Aircraft          : A32NX 
Tier of Testing   : 1
Date              : 25/10/2024

Testing Process: 
Entered KSFO 28L/R Visual Approach
Tried to create PBD but noticed that the PBD datapage still doesnt use the station declination as magvar.
For Example: I want to create an PBD Point SFO/095/20 but it automatically takes 099 instead of 095 

Testing Results: 
Not Passed  

Media:
Current Development Version:
Screenshot (179)
Screenshot (180)
Screenshot (181)

PR Build Version:
Screenshot (185)
Screenshot (182)
Screenshot (183)

**Comment by tracernz** [comment]
Needs 0.13 changelog.

**Comment by frenchairbuspilot** [comment]
QA Trainee Report

Discord          : jp320#3336
Object of testing: #9103
Tier of Testing  : 1
Date             : 30/10/2024

Testing Process: 
Spawn at EBBR 25R, entering both transition to RWY 01 FLO1E and RWY25 KERKY1R ( now RNAV but used to be conventional)
then PDBs crosscheck in data pages, values stayed the same as entered ( no screens for that page sorry)

Negatives:
Slight deviation from PDB to GPS waypoint, probably due to chart accuracy, not really an issue in the sim, PBDs are almost where they should be, within tolerances?

Testing Results: 
Passed

Conclusions: 
Didn't see any differences on ND/ waypoint data page, between PR and current DEV version

Media:
PR build:
Capture d’écran 2024-10-30 081223
Capture d’écran 2024-10-30 081602

Current DEV f64ef67
Capture d’écran 2024-10-30 082715
Capture d’écran 2024-10-30 083432

**Comment by 2hwk** [comment]
Needs changelog.md entry

**Pull request merged**
