### PR TITLE
chore: lint a380x/systems-host + shared

### PR DESCRIPTION
**Pull request by flogross89**
## Summary of Changes

- Runs lint on a380x's systems-host and systems/shared
- fix import in notification.ts: KeyInterceptManager -> KeyEventManager
- fix reference path import in popup.ts

### CODE REVIEW

**Comment by tracernz** [comment]
Duplicate of https://github.com/flybywiresim/aircraft/pull/8956 ?

**Comment by flogross89** [comment]
> Duplicate of #8956 ?
Yup it's partly duplicate, but the other PR doesn't seem to have activity, and a bunch of merge conflicts. Doesn't seem to be merged within the next days. I need this PR for another PR though.

**Review by 2hwk — APPROVED** [review]

**Comment by tracernz** [comment]
Have you discussed with the maintainer of the other PR? It is approved and ready to be merged when conflicts are solved.

**Comment by flogross89** [comment]
duplicate to #8956

**Pull request closed without merging**
