### PR TITLE
fix(GSX/Refuel): Allow Refuel Process to finish when GSX L-Vars go 0 due to SimConnect Issues

### LINKED ISSUE #8434: GSX refueling truck issue
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-20T14:55:29+00:00",
    "ref": "refs/heads/master",
    "sha": "9f9e8313cab268c6414cfc3fe6db3c40c199a054",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:9f9e8313",
    "version": "v0.12.0-dev.9f9e831"
}
```

### Describe the bug

When the GSX payload and Fuel is synced, I call a fuel truck to reful as per simbrief loaded flight plan, by clicking the little cloud to load in the data, the fuel truck usually when starting the sim will arrive fuel and leave, however sometimes he will arrive start fueling and stop when not even 1/2 the requested amount is fueled, this from starting the sim happens very little, but it happens every time when doing a turn around. 

when doing a turn around he arrives, loads 1/4 or 1/2 at most fuel and leaves and I have to ask him to come fuel again and at which point he finishes the job. 

### Expected behavior

I except him to arrive fuel the expected amount and leave at the first time of asking.

### Steps to reproduce

During a turn around. 

Arrive,
Deboard,
Download new OFP and fuel and payload amounts. 
Request refuel via GSX 
Now because of an update if set to real he will start refueling on his own, and he will randomly stop and drive away.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

kris.novak

### PR DESCRIPTION
**Pull request by Fragtality**
Fixes #8434

## Summary of Changes

- Removed Calls in the Fuel Page format...() Functions resetting the *A32NX_REFUEL_STARTED_BY_USR* L-Var to false
  - The Refuel Function in A32NX_Refuel.js already did this and should be the only Place which decides that
- Changes in A32NX_Refuel.js so that said L-Var is set back to false when Instant was used

That would be my Proposal based on similar Cases with Fenix2GSX. (More on that in the linked Issue)

I'm not sure if that should have a Changelog Entry? If not: please remove :)

## Additional context

- The Refuel Process should now continue when the GSX L-Var (*FSDT_GSX_FUELHOSE_CONNECTED*) goes to 0 for any Reason
- It should also continue when GSX is crashed/restarted

Discord username (if different from GitHub): Fragtality

## Testing instructions

Synthetic Test:
- Set FSDT_GSX_FUELHOSE_CONNECTED to 0 while Refueling is active ("pumping")

Test:
- Affected Users need to recreate the Situation where this happens

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Note for QA: Need to test with and without GSX

**Comment by TTTTdayjunior** [comment]
So once downloaed the 2gb file, essentially refuel on stand fly and arrive and request refuel to see if tis ok now? 

Before doing this, the last 2-3 flights i've done it seems to have been ok.. but if this is what you need me to do ill go ahead this evening.

**Comment by Fragtality** [comment]
Yeah, just commence a Flight like you normally would (if possible as close to the Situations where it happened) :)

**Comment by TTTTdayjunior** [comment]
Not to be dim but as I understand it the 2gb file is a updated development version of the FBW which is in the testing process due to this issue, sorry new to this just want to know what i'm downloading.

**Comment by Fragtality** [comment]
Yeah it is the complete Aircraft in the current Development Version plus that Fix but manually installed from a Zip :)

**Comment by Saschl** [comment]
QA Tester Report

Discord : saschl
Object of testing:https://github.com/flybywiresim/aircraft/pull/8437
Tier of Testing : 1
Date : 04/02/2024

Testing Process:
1. Flight from LOWW to LOWI, fueling with GSX -> All planned fuel was loaded
2. Turnaround flight, loaded fuel and set LVAR to 0, fueling continues in the plane until planned fuel is reached
3. Fueling without GSX -> works just as before

Negatives:
none

Testing Results:
Passed

Conclusions:
Fueling did not stop prematurely ;)

**Pull request merged**
