### PR TITLE
fix(ecam): misaligned ecam memo items

### PR DESCRIPTION
**Pull request by tyler58546**
## Summary of Changes

Fixed misaligned items on ecam memos.

## Screenshots (if necessary)

Before:
image

After:
image
image

## References

image

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by beheh** [comment]
I don't trust that documentation for the precise alignment. A reference photograph shows me that it's too many dots now:

image

**Comment by tyler58546** [comment]
Fixed
image

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #6031
Tier of Testing: 1
Date: 17/10/2021

Testing Process:
- Spawned on runway at EDDP 
- Turned off TO conf, Cabin Ready is not reversible (Image1)
- Took off and activate APP phase, below 2500ft landing memo appears (Image2)

Negatives: Conf3 still shows "Full" and disappears only with full flaps (part of this PR?) (Image3)

Testing Results: -
Conclusions: PR looks good. But the Conf3 thing needs to be fixed.

Hope this helps :-)


Image1


Image2


Image3

**Comment by beheh** [comment]
> Negatives: Conf3 still shows "Full" and disappears only with full flaps (part of this PR?) (Image3)

CONF 3 for the memo is (realistically) switched via the GPWS Flaps 3 pushbutton in the overhead panel - the MCDU setting is ignored. Also not part of this PR.

**Pull request merged**
