### PR TITLE
feat(a380x): Update Initial Fuel Levels

### LINKED ISSUE #9321: A380 - More realistic starting values for weight/fuel
### Aircraft Version

Stable

### Description

when loading up cold and dark, its unrealistic to have high fuel capacity and leads to the plane being defueled most of the time which is not realistic at all.

a more realistic value would be around 10/20t 

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

samueleonard

### PR DESCRIPTION
**Pull request by sschiphorst**
Fixes #9321 

## Summary of Changes

Changes to the starting fuel in all tanks to better represent a real life starting load. 
Fuel is down from ~180 tonne to 15 tonne, allowing more people to fuel the plane rather than defuel the plane during ground ops. 
Tank balance was taken from replicating the load within the EFB in current release. 

## Additional context

Discord username (if different from GitHub): Yahtzee94

## Testing instructions

1. Open aircraft on ramp or runway
2. Verify in EFB and SD that fuel is total to 15000kg 
3. Verify in EFB and SD that fuel is 3750kgs in feed tanks 1 through 4 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by sschiphorst** [comment]
> Needs testing instructions

Added - knew I was forgetting something

**Comment by donstim** [comment]
AFAIK, starting cold and dark the initial fuel load (after at least one flight) will be the ending fuel load for the previous flight for that livery. If that is correct, then this change will only apply to the first flight in a given livery and for starting other than cold and dark.

**Comment by Saschl** [comment]
Whats the reason for closing your PR?

**Comment by sschiphorst** [comment]
> Whats the reason for closing your PR?

Made an error when tidying up forks on my repository!

**Comment by Awemeter** [comment]
Quality Assurance Trainee Report

Discord Username: Awemeter
Object of testing: #9397
Aircraft: A380X 
Tier of Testing: 1
Date: 8/11/2024 

Testing Process: 
 
Installed A380 4k artifact in community folder.
Loaded into aircraft on the ramp
Verified in EFB and SD that fuel is total to 15000kg
Checked in EFB and SD that fuel is ~5200kgs in feed tanks 1 through 4
Testing Results: 
Not Passed  

Negatives:       

Feed tanks 1-4 are at 3750kg instead of 5200kgs
Conclusions: 

PR failed due to EFB feed tanks not at the specified amount but I'm not sure how its possible to be at 5200kgs while the total fuel is 1500kg. I might be misunderstanding the testing instructions or a possible typo.
Media:

image
image

**Comment by sschiphorst** [comment]
> Quality Assurance Trainee Report
> 
> Discord Username: Awemeter Object of testing: #9397 Aircraft: A380X Tier of Testing: 1 Date: 8/11/2024
> 
> Testing Process:
> 
> Installed A380 4k artifact in community folder. Loaded into aircraft on the ramp Verified in EFB and SD that fuel is total to 15000kg Checked in EFB and SD that fuel is ~5200kgs in feed tanks 1 through 4 Testing Results: Not Passed
> 
> Negatives:
> 
> Feed tanks 1-4 are at 3750kg instead of 5200kgs Conclusions:
> 
> PR failed due to EFB feed tanks not at the specified amount but I'm not sure how its possible for each feed tank to be at 5200kgs when the total fuel is 1500kg. I might be misunderstanding the testing instructions or a possible typo. Media:
> 
> image image

This is why I should actually think before I type things at 2am. It was indeed a typo. Tanks should be at 3750kg each as tested.

**Review by 2hwk — APPROVED** [review]

**Pull request merged**
