### PR TITLE
fix(ND): Track line not visible in GA TRK or RWY TRK modes (#9474)

### LINKED ISSUE #9474: ND: Track line not visible in GA TRK or RWY TRK modes
### Aircraft Version

Stable

### Build info

```json
N/A
```

### Describe the bug

Green track line is not visible on the ND when FG lateral mode is RWY TRK or GA TRK. In addition, even when RWY is active without NAV mode armed, it should show.

### Expected behavior

Green track line to be visible in the conditions mentioned above.

### Steps to reproduce

Preselect heading during departure and observe the ND after RWY TRK engages or RWY engages (if available), or, preselect heading during approach and perform a go around.

### References (optional)

https://youtu.be/xQVfljH0a3E?t=86
https://youtu.be/OJF8mMBMFcQ?t=61
https://youtu.be/pHui34_ODnc

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by ta-dzik**
Fixes #9474

## Summary of Changes

added trackline for RWY, RWY TRK and GA TRK lateral modes

## References

References are in the bug

## Additional context

Discord username (if different from GitHub): Ta_dzik

## Testing instructions

Tested using reproduction instruction in the bug.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Comment by 2hwk** [comment]
Lint is failing (prettier)

**Comment by ta-dzik** [comment]
squashed commit to make linter happy and synced fork - not sure how I could have done this better with GitHub to avoid force-push

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Quality Assurance Tester Report

Discord Username: 2cas
Object of testing: #9513
Aircraft:  A380X
Tier of Testing: 1
Date: 15/11/2024 

Testing Process: 
- [x] Preselect heading during departure and observe the ND after RWY TRK engages or RWY engages (if available)
- [x] Preselect heading during approach and perform a go around.

Testing Results: 
QA Passed

Negatives:       
- N/A

Conclusions: 
- LGTM

**Comment by 2hwk** [comment]
Congratulations on your first merged contribution! Check on discord as you will receive the contributor role shortly.

**Pull request merged**
