### PR TITLE
fix(isis): alt tape order for negative altitudes

### LINKED ISSUE #7898: bug(isis): alt tape is upside down when digits are -ve
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-03-24T10:32:43+00:00",
    "ref": "HEAD",
    "sha": "b2d7668d7dcbef695cf7462635c9800234b5967c",
    "actor": "Frank Kopp <frank@familie-kopp.de>",
    "event_name": "manual",
    "pretty_release_name": "master:b2d7668d",
    "version": "v0.10.0-dev.b2d7668"
}
```

### Describe the bug

image

### Expected behavior

20 40 80 00 should be 00 20 40 80 from top to bottom below 0 feet.

### Steps to reproduce

1. Turn on and wait for ISIS to align.
2. Wind baro knob until alt is -ve.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by aweissoertel**
Fixes #7898

## Summary of Changes

For negative altitudes, the ISIS used to display altitudes in this order: 
```
80
60
40
20
00
``` 
But this only makes sense for positive altitudes because a higher altitude of the aircraft is also located higher up in the tape. Consequently, the tape should be flipped for negative altitudes like so:
```
00
20
40
60
80
```
This not only applies for the last two digits of an altitude reading shown here, but of course for the other digits and their tapes as well.

## Screenshots (if necessary)

Before:
before
After:
after

## References

reference

## Additional context

Discord username (if different from GitHub): squab_

## Testing instructions

Spawn on a runway which is as close to sealevel as possible (I used EHAM). Wait for the ISIS to allign and then you can play around with the baro knob of the ISIS. Turn it down, until a negative altitude is displayed and have a look at the alt tape. Turn it back up and look at the positive altitude tape. They should be as described above. The alt tape should be free of any jumping and shouldn't have any weird numbers.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by auroraisluna** [comment]
QA Report

Discord: alepouna
Object of testing: #8101
Tier of Testing : 1
Date : 20/7/2023

Testing Process:
- Spawn on EHAM
- Move ISOS baro around and notice for any issues

Testing Results:
Passed

**Review by BlueberryKing — APPROVED** [review]
LGTM. Out of curiosity, did you compare this code to the same logic on the PFD?

**Comment by aweissoertel** [comment]
@BlueberryKing I checked the PFD and it has the same logic as the ISIS prior to my changes. So I can create a new PR to fix the PFD as well (mentioned in #7729)

**Comment by BlueberryKing** [comment]
> @BlueberryKing I checked the PFD and it has the same logic as the ISIS prior to my changes. So I can create a new PR to fix the PFD as well (mentioned in #7729)

Thank you for checking! I didn't realize that this was still an issue on the PFD. Yes, a new PR would be greatly appreciated 😄.

**Comment by auroraisluna** [comment]
QA Report Re-Requested by BBK

Discord: alepouna
Object of testing: https://github.com/flybywiresim/aircraft/pull/8101
Tier of Testing : 1
Date : 23/7/2023

Testing Process:
- Spawn on EHAM
- Move ISIS baro around and notice for any issues

Testing Results:
Passed

Notes: 
As described in the comments, indeed the PFD suffers from the issue this PR fixes in ISIS. Fun stuff!

**Comment by lukecologne** [comment]
> @BlueberryKing I checked the PFD and it has the same logic as the ISIS prior to my changes. So I can create a new PR to fix the PFD as well (mentioned in #7729)

I want to note that I have been working on a completely different method of animation the altitude readout, which basically just shifts the scrollers with translate and changes the text in them. I think this is a much better method since it does not require the looping that the current method does, and does not create new elements each update. I also tried to incorporate the correct behaviour for negative altitudes, but I never found the time to complete it.
My work so far is pushed here: https://github.com/lukecologne/a32nx/tree/pfd-scroller-fix
Unfortunately the branch has become quite stale, but maybe you'll find it useful.

**Pull request merged**
