### PR TITLE
chore(efb): Move Auto-Simbrief Import to 3rd party

### PR DESCRIPTION
**Pull request by alepouna**
## Summary of Changes

Moves the auto-simbrief import setting to the 3rd party settings. Considering this is part of the Navigraph/Simbrief integration, I think it's only appropriate for this setting to be grouped together with it. 

## Additional context

Discord username (if different from GitHub): alepouna

## Testing instructions

Test functionality is the same as before. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by 2hwk** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/settings/

Note: Will also have to be updated if accepted.

**Comment by frankkopp** [comment]
@alepouna could you create an Issue on the docs repo to update documentation for this? Thanks

**Review by frankkopp — APPROVED** [review]

**Comment by alepouna** [comment]
> @alepouna could you create an Issue on the docs repo to update documentation for this? Thanks

Yeah was planning on opening a PR there as well there once I was on the sim to grab pictures, will do!

**Comment by alepouna** [comment]
Docs PR has been opened. https://github.com/flybywiresim/docs/pull/946

**Comment by 2hwk** [comment]
Remember to merge with docs changes above

**Review by 2hwk — APPROVED** [review]

**Comment by Popespice** [comment]
Quality Assurance Trainee Report

Discord          : Popespice
Object of testing: #8548 
Tier of Testing  : 1
Date             : 25/03/2024

Testing Process: A32NX
1. Log into sim
2. Load into plane as usual
3. Turn on flypad
4. Go to Settings
5. Click 3rd party options
6. Toggle ON "Automatically Import Simbrief Data"
7. Restart sim
8. Repeat steps 1, 2, 3
9. Observe upon turning on flypad, and assuming a simbrief flight plan has been generated, plan will populate automatically in flypad

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Works as expected

Media:       
N/A

**Comment by pilotseyea350** [comment]
Quality Assurance Trainee Report

Discord : PilotEyesA350
Object of testing: #8548
Tier of Testing : 1
Date : 26/03/2024

Testing Process:

Plan a flight into Simbrief ; In this case the flight was  : FW320/FBW320 from EDDM to EDDF
Launch the sim
Spawn at stand 606 at EDDM
Turn on flypad
Go to Settings
Click 3rd party options
Enter Simbrief ID
Toggle ON "Automatically Import Simbrief Data"

Observe Message "The override Simbrief Pilot ID had been validated and updated to ...."
Observe Message "Fuel and Payload imported!"
Observe "Your Flight" & "Important Information" categories have been correctly populated
Observe OFP available in "Dispatch"
Observe Planned Weights in the flyPad are the same as simbrief's

Negatives:

N/A

Testing Results:
Passed

Conclusions:
Test passed

Media:
N/A

**Pull request merged**
