### PR TITLE
feat(ND): add default msfs weather radar

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #[issue_no]

## Summary of Changes

Another attempt on adding the WXR to the plane. This time using the msfs-avionics framework for configuring the map. The ND only displays which should avoid a negative performance impact.

Also bumps msfs-avionics to 0.3 which helps a lot in displaying the radar.

## Screenshots (if necessary)

Microsoft Flight Simulator 05_10_2022 00_02_59

## Additional context

Todo:

- [ ] Proper masking and positioning
   - [x] Arc Mode
   - [x] Rose Mode
- [ ] Tweak the colours if possible
- [x] Remove unused code of msfs-avionics
- [x] Add both sides independently
- [x] Implement in ND-V2 ;)

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by ErikNL80** [comment]
Hi guys, what is the status on this one? Today a mod appeared at flightsim.to based on the current dev ND. This could cause potential support issues... Hope you can merge this one for now, just as with the working wipers.

**Comment by tracernz** [comment]
@ErikNL80 This is not feasible at all, as the bing map uses a different map projection to the ND, so everything will be misaligned, especially further from the aircraft, and at more extreme latitudes.

**Comment by ErikNL80** [comment]
> @ErikNL80 This is not feasible at all, as the bing map uses a different map projection to the ND, so everything will be misaligned, especially further from the aircraft, and at more extreme latitudes.

Ok, why is this PR open if not feasible? Just asking :)

**Comment by NUTTTTTTTT** [comment]
> Ok, why is this PR open if not feasible? Just asking :)

ok fixed. thanks @Saschl 🚀

**Pull request closed without merging**
