### PR TITLE
fix: QFE text missing

### LINKED ISSUE #8478: FCU: QFE text missing
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-02-09T12:00:46+00:00",
    "ref": "refs/heads/master",
    "sha": "49ee675cd43ab234e9b9adc04198c4bb4338dac2",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:49ee675c",
    "version": "a32nx-v0.12.0-dev.49ee675"
}
```

### Describe the bug

"QFE" text is missing on the FCU despite being visible on the PFD
QFE
QFE1

### Expected behavior

QFE text should be visible on the FCU since it is possible to toggle QFE.

### Steps to reproduce

Toggle QFE by left clicking the baro selector or perform the annunciator light test.

### References (optional)
image

_No response_

### Additional info (optional)

IIRC it was visible on the old FCU/pre model update. 

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by BenJuan26**
Fixes #8478 

## Summary of Changes

* Add the optional parameter `classPrefix` to the FCU's `setTextElementActive()` function
  * This is necessary because, unlike the rest of the text elements in the FCU, these ones are identified by class rather than ID, because there are left and right versions
* Use `setElementVisibility()` instead of manually setting the display value

### Before:

QNH displayed despite QFE being selected:

image

QFE missing in lights test:

image

### After:

QNH on both FCU and PFD:

Screenshot 2024-02-19 195319

QFE on both FCU and PFD:

Screenshot 2024-02-19 195332

STD on both FCU and PFD:

Screenshot 2024-02-19 195348

Lights test:

Screenshot 2024-02-19 195428

## References

This is behaviour that existed previously and began malfunctioning, seemingly starting with #8334 

## Testing instructions

1. Load into a flight cold and dark
2. Connect the external power and turn on the batteries
3. Push in the pressure mode selector and observe that it switches to QFE. Push it again and it switches to QNH. Push it once more and it switches to QFE.
4. Pull the pressure mode selector and observe that it switches to STD
5. Push the pressure mode selector and observe that it returns to QFE, which was the previously selected mode
6. Turn the annunciator light switch to TEST and observe `QFE QNH` and `88.88`

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by tracernz** [comment]
We never had this param before so I don't understand why it would be needed now... I'd like to have a deeper look at this.

**Comment by BenJuan26** [comment]
Here is the commit that separated the FCU into left and right, and thus made the change from id to class: https://github.com/flybywiresim/aircraft/pull/8334/commits/39d7ac4519a9af15b6a5231bf76773d762cac7d5

**Comment by 2hwk** [comment]
> Edit: [this change is much cleaner](https://github.com/flybywiresim/aircraft/commit/8f99e7be5e662f3556c670949e7638f5221ca1d6). If you agree, I'll change this branch to use it. It has the same effect.

Yes please

**Comment by tracernz** [comment]
Makes sense @BenJuan26 and the new change looks nicer :+1:. I've done the other half, disabling QFE in https://github.com/flybywiresim/aircraft/pull/8527. This PR is still relevant for the ANN LT TEST.

**Review by tracernz — APPROVED** [review]

**Pull request merged**
