### PR TITLE
feat(a380/mfd): add automatic perf page switching depending on fms phase

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #[issue_no]

## Summary of Changes

Adds automatic page switching on PERF page depending on FMS flightphase.
## References

https://youtu.be/pHui34_ODnc?t=105

## Additional context

Discord username (if different from GitHub):
bruno_pt99
## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
Should this only switch if you're on the active phase page?

**Comment by BravoMike99** [comment]
> Should this only switch if you're on the active phase page?

Sounds logical if it works that way but I couldn't find any refs other than the video above sadly. If you can confirm that's the expected behavior ill add that logic (is that also how the 320 works?).

**Comment by tracernz** [comment]
According to my info the A320 pages should only sequence to the next flight phase from the current one (but keep in mind "next flight phase" doesn't mean the next in numerical sequence, rather the next one activated). I don't know about the A380.

**Comment by BravoMike99** [comment]
I have added that logic in the meantime if its ok by you, unless they implemented that in some recent software update I don't see why it shouldn't be similar on the A380.

**Review by tracernz — APPROVED** [review]

**Pull request merged**
