### PR TITLE
docs: Update FMS page progress Markdown

### PR DESCRIPTION
**Pull request by flogross89**
## Summary of Changes

Fixes some markdown

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by NathanInnes** [comment]
I cant stop staring!

**Comment by stanleyj138** [comment]
<3

**Review by Saschl — COMMENTED** [review]
‎

**Comment by ritiiqmsfs** [comment]
It is too late.
Everybody is staring since hours on github. :D

**Comment by AirPlaneBoy506** [comment]
cant stop us

**Comment by FBW-Git-Hub** [comment]
**Summary of Changes**

Released FBW A380. Use Installer to install the latest release.


Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

    Make sure you are signed in to GitHub
    Click on the Checks tab on the PR
    On the left side, find and click on the PR Build tab
    Click on either flybywire-aircraft-a320-neo or flybywire-aircraft-a380-842 download link at the bottom of the page

**Comment by Ani5z** [comment]
:3

**Review by svengcz — APPROVED** [review]
LGTM

**Pull request merged**
