### PR TITLE
refactor(a380x/btv): BTV architecture improvements

### LINKED ISSUE #9184: [A380X] OANS BTV fallback shows transmitted stopping distance
### Aircraft Version

Development

### Build info

```json
stable v0.12
```

### Describe the bug

When setting a manual BTV STOP DISTANCE through the OANS control panel (without Navigraph sub), after entering the desired distance, 400m of touchdown zone distance are subtracted and the input field is updated. The subtraction should happen behind the scenes. 

Furthermore, "SELECT LANDING RUNWAY IN FMS" is shown even though the landing runway is selected. 

### Expected behavior

-

### Steps to reproduce

-

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #9241: BTV not slowing down to 10kts
### Aircraft Version

Development

### Build info

```json
"built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Btv is selected and armed (BTV blue). After landing, FMA shows BTV. The btv does not slow down to arrive at the selected taxiway with 10kts but continues to overshoot the runway.

https://github.com/user-attachments/assets/f6f467c0-3aa7-4d76-86d0-53df3fdadfb9

### Expected behavior

After landing btv should activate and at a certain distance from the exit point, slow down to 10 kts as described per docs.

### Steps to reproduce

1. For your arrival airport, in the OANS select the runway and exit point
2. Put the autobrake to btv
3. verify btv blue in FMA
4. Land either manually or using autoland and monitor btv being active in the FMA with decel

### References (optional)

_No response_

### Additional info (optional)

I went on to debug the problem a little bit and discovered that the LVAR A32NX_OANS_BTV_REMAINING_DIST_TO_EXIT does not get updated.
For reference: At EDDP for RWY 26L with S4 selected as exit point, the value is always 14047249408.000 while the A32NX_OANS_BTV_REQ_STOPPING_DISTANCE is actually only 14043751424.000.

### Discord Username (optional)
dennis762

### LINKED ISSUE #9256: [A380X][ROW] Consider flight phase for warning
### Aircraft Version

Development

### Build info

```json
v0.12
```

### Describe the bug

ROW triggers when on take-off if T/O rwy is same as LDG rwy, or go-around

### Expected behavior

Shouldn't do that. Check for approach condition/phase somehow

### Steps to reproduce

-

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

floridude

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #9241 
Fixes #9184 
Fixes #9256 

## Summary of Changes

- Move remaining distance calculation to systems-host (not called from ND CAPT/FO instrument anymore)
- Fix BTV fallback entry field
- Auto-choose FMS runway if no BTV runway is set at 300ft AGL (for ROW/ROP)
- Suppress ROW if G/A after thrust reduction
- Show BTV runway info only in PLAN mode

## Additional context

Discord username (if different from GitHub):

## Testing instructions

**With Navigraph linked:**

1. Perform BTV landing, set up from the CAPT ND
2. Perform BTV landing, set up from the F/O ND
3. Test ROW: Set up correct landing runway in FMS, approach runway without setting it as landing runway in BTV. Runway should get selected automatically at 300ft. Float over the runway without landing it, ROW should alert you with "RWY TOO SHORT". Go around and immediately reduce to CLB thrust. ROW should not activate anymore when climbing

**Without Navigraph linked:**
1. Perform BTV landing, set up from the F/O ND using the fallback dialog (MAP DATA in the OANS control panel)

Tip: You can just slew backwards to set yourself up for the approach once again, or fly patterns if you want to. Make sure to get above 1000ft AGL though. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Review by 2hwk — APPROVED** [review]

**Comment by BravoMike99** [comment]
Quality Assurance Report

Discord Username : bruno_pt99
Object of testing : #9355 
Aircraft : A380X
Tier of Testing : 1
Date : 04/11/2024

Testing Process:
Quick patterns around LPBJ without navigraph charts linked as i am a non navi pleb :D 

1) Performed a quick pattern and floated all over RWY 19R at around 20-30FT AGL.
2) Once runway too short callout triggered, I initiated go around and immediately reduced the thrust levers to climb. Runway too short callout did not trigger during the climb out.
3) Attempted a BTV landing with manual fallback and it worked as expected.

Negatives:
As soon as I set selected the landing runway on the MFD in the air the BTV19R/MANUAL appeared on top of the ND and the BTV distance was set to the whole runway length, not sure if this is expected.
BTV
BTV2

Testing Results:
Passed

**Comment by flogross89** [comment]
@BravoMike99 Thanks a lot for the test! It should indeed only set the BTV runway if you enter a distance, just pushed a commit fixing that. Could you run a quick test to see whether it behaves as expected?

**Comment by flogross89** [comment]
[navigraph-fix.zip](https://github.com/user-attachments/files/17668512/navigraph-fix.zip)
Needed for tests with Navigraph, extract to flybywire-aircraft-a380-842\html_ui\Pages\VCockpit\Instruments\A380X\ and overwrite files.

**Comment by nebj00la** [comment]
Quality Assurance Trainee Report

Discord Username  : nebj00la
Object of testing : #9355
Aircraft          : A380X
Tier of Testing   : 1
Date              : 07/11/2024

Testing Process: 

1. Loaded various waypoints for approach to KBOS.
2. Configured BTV landing configuration with and without Navigraph. With successfully stopped at the chosen runway intersection. Without successfully stopped the aircraft at the configured distance.

Testing Results: 
Passed

Media:

9355-1-CP
9355-2-CP
9355-3-CP
9355-4-CP
9355-5-CP
9355-6-CP

**Comment by BravoMike99** [comment]
> @BravoMike99 Thanks a lot for the test! It should indeed only set the BTV runway if you enter a distance, just pushed a commit fixing that. Could you run a quick test to see whether it behaves as expected?

It is fixed with the latest commit & BTV manual fallback still works as expected  with no regressions 👍

**Pull request merged**
