### PR TITLE
fix(a32nx): FMS: Only check "TO SPEEDS TO LOW" condition if V speeds are set

### PR DESCRIPTION
**Pull request by flogross89**
Fixes issue, where "TO SPEEDS TO LOW" is triggered when setting flaps, but no V speeds.

## Summary of Changes

only check "TO SPEEDS TO LOW" condition if V speeds are set

## Additional context

Discord username (if different from GitHub): floridude

## Testing instructions

1. Fill in MCDU except up to PERF/T.O data
2. First enter take-off flaps, this should NOT trigger the message
3. Then insert plausible V1, VR, V2, this should NOT trigger the message
4. Then try clearing the fields, and entering inplausible (< 100kts) V speeds, and see whether the message triggers correctly, even after inputting only one V speed

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by becas22** [comment]
Looking at the code, it seems that you have to insert all the v speeds before you get the message.

According to FCOM, just one v speed is enough:

`The flight crew inserts at least one takeoff speed (V1, VR or V2) that is below the corresponding
minimum speed determined by the FMS, based on VMCG, VMCA and VS1G.
Associated with an ECAM alert.`

**Review by 2hwk — APPROVED** [review]

**Comment by tracernz** [comment]
> Looking at the code, it seems that you have to insert all the v speeds before you get the message.
> 
> According to FCOM, just one v speed is enough:
> 
> `The flight crew inserts at least one takeoff speed (V1, VR or V2) that is below the corresponding minimum speed determined by the FMS, based on VMCG, VMCA and VS1G. Associated with an ECAM alert.`

That’s the behaviour we had before too. This PR changes it.

**Comment by flogross89** [comment]
@becas22 thanks for the ref. The latest commit also checks after inputting one v speed.

**Comment by Aleloplt** [comment]
Quality Assurance Tester/Trainee Report

Discord: Alelo
Object of testing: https://github.com/flybywiresim/aircraft/pull/8768
Tier of Testing: 1
Date: 28/07/24

Testing Process:
Testing as per the instructions. Multiple resets to check.

Negatives:
NA

Testing Results:
Passed

Tes2
test3

**Comment by Aryeh123is** [comment]
Quality Assurance Tester/Trainee Report

Discord: Aryeh123is
Object of testing: #8768
Tier of Testing: 1
Date : 01/08/2024

Testing Process: 
Done as said in the 'Testing Instructions' section.

Negatives:       
NA

Testing Results: 
Passed

Conclusions: 
Worked as it should.
However, as previously discussed in Discord, the calculations from the EFB are a lot higher than the figures got from FlySmart (the real calculator) with the same parameters put into both. (Shomas aided in the FlySmart side)

Media:       
Screenshot 2024-08-01 125714
Screenshot 2024-08-01 125756

**Comment by noonebling** [comment]
Quality Assurance Trainee Report

Discord          : noonebling
Object of testing: 8768
Tier of Testing  : 1
Date             : 03/08/2024

Testing Process: 
Testing done as per instructions

Negatives:
N/A

Testing Results: 
Passed

Conclusions: 
Works as expected

**Review by 2hwk — APPROVED** [review]

**Pull request merged**
