### PR TITLE
feat: Plugged-Window mesh added

### PR DESCRIPTION
**Pull request by Henrik2k17**
## Summary of Changes
Adds the ability to plug windows (livery specific).

## Screenshots
FlightSimulator_9G3Kv3QxOw copy

## Testing instructions
-Only the FBW house livery should have the first two rows plugged.
-Make sure 3rd party liveries are displayed correct (no plugs).
-Make sure the custom plugging works.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
It would be better to add this in the blender project for the fuselage I think. Do you have a blend file?

**Comment by Benjozork** [comment]
We should probably document this on our docs as well

**Comment by TJCAviation** [comment]
I would reccomend making the Plug COMP the exact same as the Fuse COMP

With the Plug COMP being full red, it can cause some issues with the lighting/shadows as the base comp is slightly different around it...so the plugs tend to be a bit brighter then the fuse with in a shadow.

See my attatched image for what I mean
FlightSimulator 2024-02-16 02-05-21

**Comment by tracernz** [comment]
We need to get the blend file and png textures for this so we can integrate into our new model build.

**Comment by tracernz** [comment]
Can this texture be a 2x2, transparent one by default? I don't think it's worth a bunch of VRAM for the tiny number of liveries that will use it.

**Comment by pilotseyea350** [comment]
This could be more relevant for the A380X, there isn't any A380 operator (current or former) that doesn't have some plugged windows

**Pull request closed without merging**
