### PR TITLE
fix(a380x/fms): Fix FMS/PERF/TO layouting issue

### LINKED ISSUE #9266: PERF Page some feature blank
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

On MCDU performance page, select options such as Flaps, THS FOR, packs, etc. disappear and are not visible

In the beginning, FLAPS, THS FOR/PACS ANTI ICE etc. are displayed normally, but when the F-PLN selects the runway at the departure airport, the item disappears

### Expected behavior

As normal, these options should be enabled, not blank

### Steps to reproduce

1. Cold and Dark cockpit flow
2. Imported Simbrief information from EFB (I plan EGLL>EGLL test flight)
3. Importing Simbrief information from MCDU INIT
4. In F-PLN, select EGLL RWY 27L SID GOGS2G and insert
5. Enter values such as ZFW, block, etc. in Fuel & Load
6. Items in Flaps, THS FOR, PACKS, ANTI ICE are blank on the PERF page in question

### References (optional)

dasda

### Additional info (optional)

_No response_

### Discord Username (optional)

monflex

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #9266 

## Summary of Changes

Reduces height of some elements, to give flex-grow some space to breathe. For some users, layout was overloaded vertically which lead to the THS FOR ... line not being rendered. 

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Complete cockpit preparation as per SOP, go to FMS/ACTIVE/PERF, confirm that page shows without layouting issue. Should look like above. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

**Comment by GLF6** [comment]
I'm glad the issue seems to have been fixed, why is this only happening to some of those users?, Is there a way to solve this problem temporarily until the next update?

**Comment by flogross89** [comment]
> I'm glad the issue seems to have been fixed, why is this only happening to some of those users?, Is there a way to solve this problem temporarily until the next update?

There's no temporary workaround unfortunately, but we're going to release this bugfix quite soon

**Comment by GLF6** [comment]
> > I'm glad the issue seems to have been fixed, why is this only happening to some of those users?, Is there a way to solve this problem temporarily until the next update?
> 
> There's no temporary workaround unfortunately, but we're going to release this bugfix quite soon

Thank you, but why is that problem happening to me? I've tried a number of reinstall but the symptoms are still there, Most users seem to be rare to have a problem with the issue

**Comment by stefanodat** [comment]
Thank you for addressing the bug so quickly and fixing it for the next update.
Having seen the amount of traffic in the discord support forums, I wanted to let you know how much your time and effort is appreciated.

**Comment by stefanodat** [comment]
> > > I'm glad the issue seems to have been fixed, why is this only happening to some of those users?, Is there a way to solve this problem temporarily until the next update?
> > 
> > 
> > There's no temporary workaround unfortunately, but we're going to release this bugfix quite soon
> 
> Thank you, but why is that problem happening to me? I've tried a number of reinstall but the symptoms are still there, Most users seem to be rare to have a problem with the issue

I may have a temporary resolution you could try - I cannot guarantee it will work, but try it and let me know. I got it to work twice in succession, but I do not have the time right now to do extensive testing.
1. Enter all info as normal until you get the issue.
2. On the right hand panel, click the swap button and confirm.
3. This will move what is on the right panel to the left panel.
4. Then use the performance drop down on the left hand side to go back to the peformance page with the issue and hopefully, the dropdowns we could not see before, appear.

**Comment by flogross89** [comment]
The fix is already released with 0.12.1, so no need for a temporary workaround

**Comment by GLF6** [comment]
The issue has been resolved, thank you so much!

**Comment by flogross89** [comment]
> The issue has been resolved, thank you so much!

Great to hear, you're welcome :)

**Comment by stefanodat** [comment]
Excellent stuff - was not expecting such a quick fix. Thank you!

**Pull request merged**
