### PR TITLE
chore: upgrade msfssdk to v0.7

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #[issue_no]

## Summary of Changes

Full changelog https://github.com/microsoft/msfs-avionics-mirror/releases/tag/framework-v0.7.0
The main upside for us is FSComponent support for the SVG tspan element. We had been using some hacks before to work around the lack of support, and these are undone in this PR.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- check that the minimums field on the FMA works correctly,
- check that the vertical mode slot on the FMA works correctly,
- check that EWD warnings and memos work correctly,
- check that instruments generally function correctly.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Saschl — APPROVED** [review]
Nice

**Review by Benjozork — APPROVED** [review]

**Comment by auroraisluna** [comment]
QA Report

Discord: alepouna
Object of testing:  #8335 
Tier of Testing : 1
Date : 2/1/2024

Testing Process:
- Spawn the aircraft, start ext power, start  APU, bleed & engines

Negatives: 
ECAM EWD INOP - only shows a dash. 
image

Testing Results:
Not Passed

**Comment by auroraisluna** [comment]
QA Report

Discord: alepouna
Object of testing: https://github.com/flybywiresim/aircraft/pull/8335
Tier of Testing : 2
Date : 3/1/2024

Testing Process:
- Perform full flight

Negatives:
Minimums Radio overlaps number
image

Notes:
V/S seems to be moving to the center when 0, unsure if this is normal behavior [have not checked sources]
image
image

Testing Results:
Not Passed

**Comment by Popespice** [comment]
Quality Assurance Trainee Report

Discord          : Popespice
Object of testing: #8335 
Tier of Testing  : 1
Date             : 16/1/2024

Testing Process: 
1. Log into sim
2. Load into any airport in A32NX
3. Start up as normal
4. Take off
5. Observe during takeoff and flight all screens working as expected, EWA memos and warnings working as expected, mins and vertical mode on FMA working normally.

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Working as expected

Media:       
N/A

**Pull request merged**
