### PR TITLE
fix(a380): fix seatbelts tooltip

### LINKED ISSUE #9084: A380X: incorrect tooltip label for seat belts
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-16T08:50:19+00:00",
    "ref": "refs/heads/master",
    "sha": "776ca1fa8299500a7bfb4d6c4d7c567c6eaf2ef7",
    "actor": "mjuhe",
    "event_name": "manual",
    "pretty_release_name": "master:776ca1fa",
    "version": "a380x-v0.12.0-dev.776ca1f"
}
```

### Describe the bug

The tooltip for the seat belts switch incorrectly shows "NO SMOKE" on it.

### Expected behavior

It should say something along the lines of 'TURN OFF "SEAT BELTS" PROMPT LIGHT".

### Steps to reproduce

1. Hover over the seat belt switch until the tooltip appears

### References (optional)

image
image
image

### Additional info (optional)

This bug also occurs in other switch states. (See references for more info)

### Discord Username (optional)

ccute

### PR DESCRIPTION
**Pull request by thomasshrm**
Fixes #9084 

## Summary of Changes
fixing seat belts tooltip displaying on seat belts switch

## Additional context

Discord username (if different from GitHub): tommytknuckles

## Testing instructions

Reviewer need to check if the attribute is in fs_base. I currently don't have access to my computer with MSFS installed. Thank you

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
You can update existing PRs rather than opening a new one. These keys are good now, except the AUTO one doesn't exist, but that problem already existed for NOSMOKE as well so it's okay.

**Comment by thomasshrm** [comment]
> You can update existing PRs rather than opening a new one. These keys are good now, except the AUTO one doesn't exist, but that problem already existed for NOSMOKE as well so it's okay.

Thank you for the information, I ain't that familiar with Github.

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord Username  : 2cas
Object of testing : #9126
Aircraft          : A380X
Tier of Testing   : 1
Date              : 29/10/2024

Testing Process: 

 - [x] Checked Seatbelt Tooltip is corrected

Negatives:
- N/A

Testing Results: 
Passed

**Comment by 2hwk** [comment]
Needs Changelog

**Pull request merged**
