### PR TITLE
feat(a380x/efb): Added cabin lighting controls to EFB

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #[issue_no]

## Summary of Changes

- Added cabin light slider (a380x only) - In Quick Settings and Settings > Sim Options
- Added cabin auto-brightness toggle (A380x only)- In Quick Settings and Settings > Sim Options
- Also included having Traffic Filter ON during spawn state on runway/climb/cruise/descent/approach/final - missing addition from previous PR (a380x only)

## Screenshots (if necessary)

image
image

## Additional context

For repsol

Discord username (if different from GitHub):

## Testing instructions

- Quick Settings
  -  Check that autobrightness toggle and manual brightness slider works
- Settings > Sim Options
  -  Check that autobrightness toggle and manual brightness slider works
  - Check that localisation strings are present for both hovertext (in quick settings) and in the Settings page.
  
**Cabin Automatic Brightness**

* Cabin lighting during the day when under auto-brightness should always be 0% (off)
* Cabin lighting at night should be at 85% when at the gate, then 1% (dimmed) after engine start through takeoff.
* After takeoff: 0%, through climb/cruise and until when first entering descent phase - lights go on (5%), then off (0%)
* During approach phase and landing, lighting should be dimmed (1%).
* After engine shutdown and after parking at gate - 85%. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by alepouna — APPROVED** [review]

**Comment by pilotseyea350** [comment]
Quality Assurance Tester Report

Discord Username  : PilotEyesA350 
Object of testing : #9093 
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 29/10/2024 

Testing Process: 
1. Turn EFB On
2. Checked in quick settings that auto brightness and slider worked correctly
3. Checked in settings => sim option that auto brightness and slider worked correctly 

Testing Results: 
Passed  

Negatives:       
N/A

Conclusions: 
N/A

Media:
N/A

**Comment by pilotseyea350** [comment]
Actually the ambient light knob still controls the brightness. If ambient light is off + efb lightning control is above 0%, cabin lights don't work, if ambient light is turned on, (one click to the right) then the efb control works.

**Comment by 2hwk** [comment]
If ambient lighting knob is still working for this then there is still an issue somewhere, will look into this later.

**Comment by 2hwk** [comment]
Reminder to myself to remember to add the keys to localezy

**Comment by alepouna** [comment]
> Reminder to myself to remember to add the keys to localezy

There :)

**Comment by LunakisDev** [comment]
Quality Assurance Trainee Report

Discord Username  : LunakisLeaks
Object of testing : #9093
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 5/11/2024

Testing Process: 
 
1. I turn ON the EFB.
- Tested at various times of day 
   - Opened quick settings and tested the if auto brightness and slider work. 
   - Settings > Sim Option and tested if the auto brightness and slider work.


Testing Results: 
Not Passed  

Negatives:       

The cabin lighting sliders in quick settings & sim options don't work. Same for the AUTO cabin lighting option.

Conclusions: 

The "AMBIENT LT" knob doesn't control the cabin brightness anymore.

Media:

image

**Comment by Awemeter** [comment]
Quality Assurance Tester/Trainee Report

Discord Username: Awemeter
Object of testing : #9093 
Aircraft: A380X 
Tier of Testing   : 1
Date: 11/5/2024 

Testing Process: 
 
Downloaded A380 artifact
Placed it in community folder along with stable version 12.1.0
Loaded into aircraft
Tested functions of the ambient lighting knob and ipad cabin lighting in settings and quick menu
Testing Results: 
Not Passed  

Negatives:       

Cabin lights do not work at all.
Conclusions: 

The cabin lights don't work but I noticed that the emissive on the upper deck still illuminate when the aircraft is fully powered off. Not sure if thats specific to this PR or not.
Media:

image

**Comment by Awemeter** [comment]
Quality Assurance Tester Report

Discord Username: Awemeter
Object of testing : 9093
Aircraft: A380X
Tier of Testing : 1
Date: 9/11/2024

Testing Process:
 
Downloaded A380X artifact & A32NX artifact
Loaded into A380X
Tested functions of the ambient lighting knob and ipad cabin lighting in settings and quick menu
Loaded into A32NX
Verified cabin lighting settings are not available in flypad
Testing Results:
Passed/Not Passed  
Passed
Negatives:

Conclusions:

Looks good. Still noticed the emissive on the upper deck still illuminate regardless of cabin brightness or power state but have confirmed that is not related to this PR so will open another issue.
Media:

**Comment by 2hwk** [comment]
Localazy keys have been added

**Pull request merged**
