### PR TITLE
fix(a380x/mfd): missed approach perf page inputs

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #[issue_no]

## Summary of Changes

Changes MFD GA approach page altitude inputs so they affect the correct performance data in the FMS.
## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

1) Open PERF TO page on the MFD without any airport pair inserted in INIT A. THR RED & ACCEL fields should be empty.
2) Insert an airport city pair of two different airports on the INIT page and verify the PERF TO Page again. The inserted thrust reduction, engine out & acceleration fields should go in line with the EFB settings (airfact options/pin programs).
3) Verify the heights on the GA PERF page follow the same rule as above but based on the landing airport elevation.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
The AMI database information should come from the flyPad settings rather than hardcoded, as in the A32NX.

**Comment by BravoMike99** [comment]
> The AMI database information should come from the flyPad settings rather than hardcoded, as in the A32NX.

Makes sense. I have now removed the initialization &  heights from the AMI interface.

**Comment by BravoMike99** [comment]
> seems we got lint errors in this one?

Should be fixed now. I must have something misconfigured on my machine as those didn't appear as errors but the lint fix suggestion instead does, hence why I changed it in the first place 😅

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord Username  : 2cas
Object of testing : #8957
Aircraft          : A380X
Tier of Testing   : 1
Date              : 17/10/2024

Testing Process: 

 - [x]   Open PERF TO page on the MFD without any airport pair inserted in INIT A. THR RED & ACCEL fields should be empty.
 - [x] Insert an airport city pair of two different airports on the INIT page and verify the PERF TO Page again. The inserted thrust reduction, engine out & acceleration fields should go in line with the EFB settings (airfact options/pin programs).
 - [x] Verify the heights on the GA PERF page follow the same rule as above but based on the landing airport elevation.

Negatives:
 - Had issues trying to input Airport TO/FROM manually in the INIT page, but not related to this PR.

Testing Results: 
Passed

**Pull request merged**
