### PR TITLE
chore(a380x): Clean up MFD event handlers

### PR DESCRIPTION
**Pull request by flogross89**
## Summary of Changes

Properly define and clean up event handlers within the MFD and its components

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Click through the MFD, set up FMS, everything should work as before

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by CaptCrystal** [comment]
Quality Assurance Trainee Report

Discord Username: captcrystal
Object of testing: #9419
Aircraft: A380X
Tier of Testing: 1
Date: 08/11/2024

Testing Process: 

- Loaded in to KSFO
- Set up aircraft per usual flows 
- Set up the FMC per usual flows (Flight plan to KLAX)
- While setting up the FMC, I verified that all pages worked as expected
- Verified that all MFD pages work correctly

Testing Results: 
Not Passed

Negatives:       
FPLN Page does not show any waypoints/legs
I was able to verify via the direct page in the FMC that the plane knows what waypoints are being stored, there are just no waypoints being displayed on the FLPN page

Conclusions: 
Please review the FLPN page of the FMC

**Comment by flogross89** [comment]
> Quality Assurance Trainee Report
> 
> Discord Username: captcrystal Object of testing: #9419 Aircraft: A380X Tier of Testing: 1 Date: 08/11/2024
> 
> Testing Process:
> 
> * Loaded in to KSFO
> * Set up aircraft per usual flows
> * Set up the FMC per usual flows (Flight plan to KLAX)
> * While setting up the FMC, I verified that all pages worked as expected
> * Verified that all MFD pages work correctly
> 
> Testing Results: Not Passed
> 
> Negatives: FPLN Page does not show any waypoints/legs I was able to verify via the direct page in the FMC that the plane knows what waypoints are being stored, there are just no waypoints being displayed on the FLPN page
> 
> Conclusions: Please review the FLPN page of the FMC

Thanks for the test, I found the issue. You can re-test :)

**Comment by CaptCrystal** [comment]
> > Quality Assurance Trainee Report
> > Discord Username: captcrystal Object of testing: #9419 Aircraft: A380X Tier of Testing: 1 Date: 08/11/2024
> > Testing Process:
> > 
> > * Loaded in to KSFO
> > * Set up aircraft per usual flows
> > * Set up the FMC per usual flows (Flight plan to KLAX)
> > * While setting up the FMC, I verified that all pages worked as expected
> > * Verified that all MFD pages work correctly
> > 
> > Testing Results: Not Passed
> > Negatives: FPLN Page does not show any waypoints/legs I was able to verify via the direct page in the FMC that the plane knows what waypoints are being stored, there are just no waypoints being displayed on the FLPN page
> > Conclusions: Please review the FLPN page of the FMC
> 
> Thanks for the test, I found the issue. You can re-test :)

Got it, thanks!

**Comment by CaptCrystal** [comment]
Quality Assurance Trainee Report

Discord Username: captcrystal
Object of testing: #9419 
Aircraft: A380X
Tier of Testing: 1
Date: 09/11/2024

Testing Process: 

- Loaded in to KSFO
- Set up aircraft per usual flows
- Set up the FMC per usual flows (Flight plan to KLAX)
- While setting up the FMC, I verified that all pages worked as expected
- Verified that all MFD pages work correctly

Testing Results: 
Passed


Conclusions: 
Works as expected. However, I found it a little bit difficult to test everything regarding the MFD while on the ground (because of waypoints moving etc.). I'd argue that this PR may require QA tier 2 testing.

**Review by Benjozork — APPROVED** [review]

**Comment by flogross89** [comment]
@Awemeter Thanks for the test and the feedback! But the guidance worked, right? Meaning the AP didn‘t descend below the constraint. 
This PR doesn't touch the vertical guidance / prediction, so it would very likely also have been an issue before the PR.

**Pull request merged**
