### PR TITLE
fix: SimVar unit names

### LINKED ISSUE #8761: SimVar unit misspellings causing console errors
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-17T08:53:25+00:00",
    "ref": "HEAD",
    "sha": "cb0d80192bbc8a174f3c0d873c3ade92b4b2ee5e",
    "actor": "flogross89 <63071941+flogross89@users.noreply.github.com>",
    "event_name": "manual",
    "pretty_release_name": "master:cb0d8019",
    "version": "a32nx-v0.12.0-dev.cb0d801"
}
```

### Describe the bug

When loading the aircraft to a gate, observe the dev console for errors mentioning "Invalid unit specified: "foot per minute" and/or "Unrecognized units: "celcius".

### Expected behavior

Errors should not appear in console; should use correct unit names.

### Steps to reproduce

1. Load aircraft into gate.
2. Open dev console and search for "unit" related errors.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by ShreyasKallingal**
Fixes #8761 

## Summary of Changes

Rename instances of "celcius" to "celsius" and "foot per minute" to "feet per minute".

## Screenshots (if necessary)

N/A

## References

N/A

## Additional context

N/A

## Testing instructions

- Load aircraft into sim
- Open dev console and search for "unit" related errors
- Observe no errors :)

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
I was a little weary of just changing these without getting Boris to check as this may change the actual number returned when the simvar is read depending on what the sims “native” unit for that particular var is. If it was working properly/tuned for the way it was before it would now be wrong in that case.

**Comment by Maximilian-Reuter** [comment]
Have you checked that the vars in question don't change their value when requesting the correct unit name? Cause if they do, as Tracer mentions we do have to look at dealing with that first so we don't have issues were none were before.

**Comment by tracernz** [comment]
Dev Team QA Report

Discord Username : tracernz
Object of testing : https://github.com/flybywiresim/aircraft/pull/8762
Aircraft : A32NX
Tier of Testing : 1
Date : 08/09/2024

Testing Process:
- Loaded in sim
- Checked dev console for unit warnings, none found.
- Checked the results of requesting each of the changed vars with the old and new units to ensure they get the same result, all same.
- Tested MAN V/S, all okay.

Testing Results:
Passed

**Review by tracernz — APPROVED** [review]

**Comment by ShreyasKallingal** [comment]
Cool, thanks for the testing!

**Comment by tracernz** [comment]
Thanks for your contribution!

**Pull request merged**
