### PR TITLE
fix: use period_visual_frame in 320 fadec

### PR DESCRIPTION
**Pull request by Saschl**
## Summary of Changes

In #7835 the fadec was changed to make use of the more efficient SIMCONNECT_PERIOD_VISUAL_FRAME. Unfortunately I missed to apply this change in both the 320 and 380 code. This is solved now

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Spawn C&D and make sure engines are starting properly 
2. Spawn on the runway and make sure engines are running

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by lukecologne — APPROVED** [review]
Looks good

**Review by lukecologne — CHANGES_REQUESTED** [review]
Oh wait, I just noticed that the 380 fbw wasm still uses `ONCE`? Might want to update that in this PR as well

**Comment by Saschl** [comment]
Both fadecs use `PERIOD_ONCE` for `simConnectRequestDataAcftInfo` only. This should be fine as this method should actually only be called on startup of the gauge (there's a condition in the gauge callback) 👍

**Comment by lukecologne** [comment]
Yep, I assumed that was the case for these functions. But in the review above I was specifically talking about the FBW wasm of the a380.

**Comment by Saschl** [comment]
Not sure why my brain ignored the fact you said fbw :D will adapt it as well

**Review by lukecologne — APPROVED** [review]
Looks good

**Comment by auroraisluna** [comment]
QA Report

Discord: alepouna
Object of testing: #8170
Tier of Testing : 1
Date : 23/08/2023

Testing Process:
- [PASS] Spawn C&D and make sure engines are starting properly
- [PASS] Spawn on the runway and make sure engines are running

Testing Results:
Passed

Notes:
He forgor :scegg:

**Pull request merged**
