### PR TITLE
chore(a380x): add 380 ECAM memos for ATA 27, 28, 31, 33, and 70, and add remaining abnormal sensed procedures

### PR DESCRIPTION
**Pull request by sai-barath**
Fixes #[issue_no]
Contributing to #8739 

## Summary of Changes

Updated ECAM memos from the ATA chapters mentioned in the title to match those found in the A380. ECAM alerts for these chapters were also deleted from the memos section of EWDMessages.tsx. Remaining abnormal sensed procedures will be added to the appropriate location

## Screenshots (if necessary)

N/A

## Additional context

Discord username (if different from GitHub): NONAmr2433

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by flogross89** [comment]
Looks good so far, thank you! Will review once the checklist items are in 👌🏽

**Comment by 2hwk** [comment]
a380x releases on Feb 31st 2025

**Comment by 2hwk** [comment]
Feb 30

**Review by flogross89 — APPROVED** [review]
Awesome, thank you! Maybe you could try implementing one or two complex ABN procedures to see whether the structure I created works as intended.

**Pull request merged**
