### PR TITLE
feat(efb): Flypad Takeoff Performance Calculator

### PR DESCRIPTION
**Pull request by jbud**
Fixes #[issue_no]

## Summary of Changes
Add a takeoff performance calculator starting with flex temp

## References

For now this is a Pseudo-Calculation. It can be updated later with real-world data if it becomes available. It is based on Paul Gale's spreadsheet (https://flightsim.to/profile/galeair) and I have permission to upload my port here. I am waiting to hear the source for this data.

## Additional context

Discord username (if different from GitHub): budzique#1196

## Testing instructions
Currently asking real world pilots of the 320neo to test for accuracy
1. Download the PR for QA (shown below)
2. Open the Calculators/Performance page of the EFB
3. Input data from your real world flights
4. Comment here, or DM me on discord, or ping me in the FBW discord in #Pilot-Feedback with the results of the comparison.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by jbud** [comment]
I still need to encapsulate the flex calculator into a class and build a widget to actually display it. This is the initial commit

**Comment by frankkopp** [comment]
Out of curiosity - where do you get the correct real life data from?
Or will this just be a pseudo calculation?

**Comment by jbud** [comment]
> Out of curiosity - where do you get the correct real life data from? Or will this just be a pseudo calculation?

The data is from Paul Gale ([https://flightsim.to/profile/galeair](https://flightsim.to/profile/galeair)) who gave me permission to use it in any way. 

It's being ported to ts from my js implementation ([https://github.com/jbud/flexjs](https://github.com/jbud/flexjs)) I used his data to build. The data can be adjusted with testing to align it with how the aircraft functions in-simulator.

**Comment by frankkopp** [comment]
> > Out of curiosity - where do you get the correct real life data from? Or will this just be a pseudo calculation?
> 
> The data is from Paul Gale ([flightsim.to/profile/galeair](https://flightsim.to/profile/galeair)) who gave me permission to use it in any way.
> 
> It's being ported to ts from my js implementation ([jbud/flexjs](https://github.com/jbud/flexjs)) I used his data to build. The data can be adjusted with testing to align it with how the aircraft functions in-simulator.

Is this real life data from A320NEOs?

Tbh - hard to believe as this data is not available. Airbus protects this data and there are no official sources. Otherwise we would have build a TO Calculator a long time ago.

Pls provide references and proof that this is based on real life NEO performance data or clearly state that it is pseudo calculation. 

Certainly his first claim on the flightsim.to page is not true as this data is not freely available for the NEO:
> The spreadsheet has been developed using aircraft performance data freely published by Airbus, Boeing, British Aerospace and Bombardier. The following aircraft types are simulated, and more will be added later. You will need to download LIBRE OFFICE which is freely available and does not interface directly with MSFS, so can be safely used with any MSFS update.

**Comment by jbud** [comment]
> > > Out of curiosity - where do you get the correct real life data from? Or will this just be a pseudo calculation?
> > 
> > 
> > The data is from Paul Gale ([flightsim.to/profile/galeair](https://flightsim.to/profile/galeair)) who gave me permission to use it in any way.
> > It's being ported to ts from my js implementation ([jbud/flexjs](https://github.com/jbud/flexjs)) I used his data to build. The data can be adjusted with testing to align it with how the aircraft functions in-simulator.
> 
> Is this real life data from A320NEOs?
> 
> Tbh - hard to believe as this data is not available. Airbus protects this data and there are no official sources. Otherwise we would have build a TO Calculator a long time ago.
> 
> Pls provide references and proof that this is based on real life NEO performance data or clearly state that it is pseudo calculation.
> 
> Certainly his first claim on the flightsim.to page is not true as this data is not freely available for the NEO:
> 
> > The spreadsheet has been developed using aircraft performance data freely published by Airbus, Boeing, British Aerospace and Bombardier. The following aircraft types are simulated, and more will be added later. You will need to download LIBRE OFFICE which is freely available and does not interface directly with MSFS, so can be safely used with any MSFS update.

I've reached out to Paul to see if he has a source, else I suppose I will call this a pseudo-calculation.

**Comment by jbud** [comment]
I have a few features yet to add, but overall the flex calculator portion is ready for review.

**Comment by johnpmaguire** [comment]
Does this fit with FBW realism objective? The two screenshots of flex temp calculations I have seen from this calculator (discord screenshot 23 degs) and the above 74 degs do not seem to be realistic.

**Comment by frankkopp** [comment]
> Does this fit with FBW realism objective? The two screenshots of flex temp calculations I have seen from this calculator (discord screenshot 23 degs) and the above 74 degs do not seem to be realistic.

It does not fit which is why it is discussed here and in the core team. I recommended to not invest too much time into this work as it might never get merged. Also see tags on this PR.

**Comment by jbud** [comment]
> Does this fit with FBW realism objective? The two screenshots of flex temp calculations I have seen from this calculator (discord screenshot 23 degs) and the above 74 degs do not seem to be realistic.

So the screenshot you saw in discord was before commit: be9635f8c996c9d50251b30d6424fe61a58ecee5 where I fixed an issue with growth calculation. I was not using the growth function's linear regression properly

**Comment by tshomas** [comment]
[FLEX Comparisons.pdf](https://github.com/flybywiresim/a32nx/files/10611955/FLEX.Comparisons.pdf)


Here's some quick FLEX comparisons against the calculator and the IRL EFB. My aircraft only goes up to 69C FLEX on a sea level airfield, whereas the calculator is using the higher FLEX limit I assume. Also lower limit seems to not be observed yet, I have written down the calculators figures where actually TOGA would be used.

**Comment by marcsoler** [comment]
Maybe this could be added optionally through the settings page with an "unrealistic" or "pseudo" label and off by default.

As a simmer I would much prefer to have a in-cockpit solution rather than a 3rd app (also with pseudo-calculations" outside of it.

**Comment by tracernz** [comment]
> Maybe this could be added optionally through the settings page with an "unrealistic" or "pseudo" label and off by default (like the PTU sounds).
> 
> As a simmer I would much prefer to have a in-cockpit solution rather than a 3rd app (also with pseudo-calculations" outside of it.

You're aware there's already a calculator in the MCDU that always produces safe values (assuming the runway is long enough)?

**Comment by jbud** [comment]
> > Maybe this could be added optionally through the settings page with an "unrealistic" or "pseudo" label and off by default (like the PTU sounds).
> > As a simmer I would much prefer to have a in-cockpit solution rather than a 3rd app (also with pseudo-calculations" outside of it.
> 
> You're aware there's already a calculator in the MCDU that always produces safe values (assuming the runway is long enough)?

```this.v1 = this.v2 - 5;```

Takes nothing for runway condition into account or even it's length. It is a good approximation for weight but V1 is a safety speed. I've been experimenting with an alternative for V1 speed. but the main point of this post is a flex temp calculator.

**Comment by marcsoler** [comment]
> > Maybe this could be added optionally through the settings page with an "unrealistic" or "pseudo" label and off by default (like the PTU sounds).
> > As a simmer I would much prefer to have a in-cockpit solution rather than a 3rd app (also with pseudo-calculations" outside of it.
> 
> You're aware there's already a calculator in the MCDU that always produces safe values (assuming the runway is long enough)?

I do and I've been using it. Yet I prefer having something more complete (flex, rwy conditions, maybe intersections) and having the calculator in the EFB is one step closer to realism.

This seems far from something accurate but a "pseudo"-calculator in the EFB rather than an auto-fill function in the MCDU is a step closer to realism.

**Comment by tracernz** [comment]
> `this.v1 = this.v2 - 5;`

This is not just a random offset. It's chosen to ensure legal values across all scenarios (as you will find you don't get T.O SPEEDS TOO LOW ever if you use these values). 

> Takes nothing for runway condition into account or even it's length.

That's why I said "(assuming the runway is long enough)".

**Comment by donstim** [comment]
> This seems far from something accurate but a "pseudo"-calculator in the EFB rather than an auto-fill function in the MCDU is a step closer to realism.

I fail to see how a "pseudo"-calculator that provides incorrect values (not talking about just a couple of knots or a couple of degrees in Flex temp here) is better than the auto-fill function. Does your desire for a takeoff performance calculator (for immersion apparently?) override your desire for realism/accuracy?

Is it okay for some of the takeoff performance limits to not be considered in something billed as a takeoff performance calculator (i.e., accelerate-stop distance, takeoff distance, stopway, clearway, obstacle clearance, climb performance, brake energy, tire speed, VMU, VMCG, stall speed, wind speed/direction, pressure altitude, OAT, runway slope, runway condition (dry, wet, contaminated)? Which ones?

Should the calculator used the standard Airbus takeoff speed calculation methodology or the improved one, or should it provide an option to use either?

**Comment by marcsoler** [comment]
>Does your desire for a takeoff performance calculator (for immersion apparently?) override your desire for realism/accuracy?

I believe you failed to see my point...

I prefere to see the results of those "auto-fill" MCDU values in on the EFB on a calculator... I didn't talked about the formula itself nor have I tested this PR. For me it could even use the same calculation as the currently autofill returns. It's also a pseudo-calculator that returns safe values.

Now if the Airbus' MCDU has these autofill functions IRL, then well I didn't know that fact and let's sit on it ;)

**Comment by tracernz** [comment]
Moving the existing function to the EFB is something that’s been discussed before. It would just require a bit of media/management as a lot of people would probably expect it to be a full perf calculator.

**Comment by tracernz** [comment]
Closing in favour of #8678

**Pull request closed without merging**
