### PR TITLE
fix(fwc): NW STRG DISC color fix

### LINKED ISSUE #8743: fws: NW steer disconnect message amber before engine is fully started & across flights
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-04T19:47:34+00:00",
    "ref": "refs/heads/master",
    "sha": "74e195a8ce4d0b1dbe7fe7dce046f7e6c4b44aff",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:74e195a8",
    "version": "a32nx-v0.12.0-dev.74e195a"
}
```

### Describe the bug

Nose wheel steering disconnect ecam memo shows as amber before an engine is fully running and across flights when engines are off.
NW STRG

### Expected behavior

Nose wheel steering message to turn amber only after an engine is running

### Steps to reproduce

1) Spawn with engines running & shutdown the engines.
2) Connect a pushback truck of your choice (EFB, GSX etc.) and observe that the NW STRG DISC ecam memo appears in amber.
3) Start a flight with engines off, connect a pushback truck of your choice as above
4) Start an engine and observe how the NW STRG DISC memo immediately turns amber as soon as N2 starts to rise.

### References (optional)

https://youtu.be/YouKucin6fs?t=75

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by Adoggman**
Fixes #8743

## Summary of Changes

Changes when the ECAM memo NW STRG DISC turns amber to be in line with the real aircraft (~30 seconds after an engine has fully started).

## Screenshots (if necessary)

346340412-236b6d69-a100-48d2-b99d-951da364be05
NW STRG DISC should be green until 30 seconds after you start the first engine, when it should turn amber. After shutting down both engines, it will turn green again.

## References

https://youtu.be/YouKucin6fs?t=75

## Additional context

Discord username (if different from GitHub):
adoggman

## Testing instructions

NW STRG DISC shows up in the ECAM during pushback. You can get it to activate by using the EFT or GSX.
This does not change when the message shows up, but when it changes from green to amber in color.
Previously, it would turn amber as soon as either engine starts were flipped on.
Now, it should turn amber about 30 seconds after the first engine has been fully started.

Using your favorite pushback tool, test that the NW STRG DISC message shows on the ECAM when expected and appears green until 30 seconds after an engine has fully started. Test both starting with engine 1 first and engine 2 first. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Comment by BravoMike99** [comment]
The real FWC checks if either engine is running to change the color of the nose wheel steering message (just like the current logic) to amber. You can probably the issue by changing the engine state condition without needing to make it dependent on the flight phase, as the engine is considered as fully running when the state is 0 if I'm not mistaken.

**Comment by Adoggman** [comment]
> The real FWC checks if either engine is running

The video referenced does not show it working that way, it only turns amber after BOTH engines have (at least partially) started. Is there a better/more technical reference?

> the engine is considered as fully running when the state is 0 if I'm not mistaken.

If you're talking about A32NX_ENGINE_STATE:
```
OFF | 0
ON | 1
STARTING | 2
SHUTTING | 3
```

We could do something like `[1, 2].includes(this.engine1State.get()) && [1, 2].includes(this.engine2State.get()) ? 1 : 0` to make it more closely match the current logic while behaving like the referenced video.

**Comment by lukecologne** [comment]
I can't give you a reference, but it is engine1running || engine2running, but for at least 30s. That is why you observed the delay.
More precisely, running is defined here as N2 greater than some idle threshold. You can look around the rest of the pFWC code, I'm told this or a similar condition is already used multiple times for other warnings

**Comment by lukecologne** [comment]
Ah, take a look at `engine1CoreAtOrAboveMinIdle` and `engine2CoreAtOrAboveMinIdle`. These are the variables you want, you just need to add a confirm time of 30s to it.

**Comment by Adoggman** [comment]
Do you know of any places I can see that are using a timed delay as an example? It seems like adding tracking for how long the engines have been running would make this fix significantly more complicated.

**Comment by lukecologne** [comment]
Take at a look at the `NXLogicConfirmNode` that is used in the pFWC

**Comment by Adoggman** [comment]
I changed it to use `NXLogicConfirmNode `(30 seconds) and engine state.

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
@lukecologne to approve as well

**Review by beheh — APPROVED** [review]

**Comment by LunakisDev** [comment]
Quality Assurance Trainee Report

Discord: LunakisLeaks
Object of testing: #8747 
Tier of Testing: 1
Date: 17/7/2024

Testing Process:
Using EFB pushback
1. Spawned at LCLK .
2. Started the A/C.
3. Pushback (Verified that "NW STRG DISC" shows up in the ECAM during pushback).
4. Verified that "NW STRG DISC" turns amber about 30 seconds after the first engine has been fully started.
5. Tested both starting with engine 1 first and engine 2 first.
6. Same test with GSX pushback.

Negatives:
N/A

Testing Results:
Passed

Conclusions:
LGTM

**Pull request merged**
